/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.CSS.Defs
import FTQCLib.Codes.Transversal

set_option linter.unusedSectionVars false

/-! # Transversal CNOT between two copies of a CSS code

For a CSS code with parity-check matrices `(H_X, H_Z)` on `n` qubits, the
*joint two-copy stabilizer* lives in `Pauli (n + n)` and is generated by:

* X-type generators of block 1: `⟨H_X i ⊕ 0, 0⟩` for each row `i` of `H_X`,
* X-type generators of block 2: `⟨0 ⊕ H_X i, 0⟩` for each row `i` of `H_X`,
* Z-type generators of block 1: `⟨0, H_Z j ⊕ 0⟩` for each row `j` of `H_Z`,
* Z-type generators of block 2: `⟨0, 0 ⊕ H_Z j⟩` for each row `j` of `H_Z`.

Transversal CNOT (control in block 1, target in block 2) acts on these
generators by the standard CSS propagation rules:

  `X-block 1 ↦ X-block 1 + X-block 2`   (X-control propagates to target)
  `X-block 2 ↦ X-block 2`               (target X unchanged)
  `Z-block 1 ↦ Z-block 1`               (control Z unchanged)
  `Z-block 2 ↦ Z-block 1 + Z-block 2`   (Z-target propagates to control)

Every image is in the joint stabilizer, so transversal CNOT preserves
the joint stabilizer setwise. This is the algebraic core of "transversal
CNOT implements logical CNOT on CSS codes".
-/

namespace FTQCLib.Codes

open FTQCLib.Pauli FTQCLib.Gates FTQCLib.Stabilizer FTQCLib.CSS Matrix

variable {n r_X r_Z : ℕ}

/-! ## Block embeddings -/

/-- X-component of the lift of `p : Pauli n` into block 1 of
`Pauli (n + n)`. -/
def lb1X (p : Pauli n) : Fin (n + n) → ZMod 2 :=
  Fin.addCases (fun k : Fin n => p.X k) (fun _ : Fin n => 0)

/-- Z-component of the lift of `p : Pauli n` into block 1. -/
def lb1Z (p : Pauli n) : Fin (n + n) → ZMod 2 :=
  Fin.addCases (fun k : Fin n => p.Z k) (fun _ : Fin n => 0)

/-- X-component of the lift of `p : Pauli n` into block 2. -/
def lb2X (p : Pauli n) : Fin (n + n) → ZMod 2 :=
  Fin.addCases (fun _ : Fin n => 0) (fun k : Fin n => p.X k)

/-- Z-component of the lift of `p : Pauli n` into block 2. -/
def lb2Z (p : Pauli n) : Fin (n + n) → ZMod 2 :=
  Fin.addCases (fun _ : Fin n => 0) (fun k : Fin n => p.Z k)

@[simp] theorem lb1X_castAdd (p : Pauli n) (k : Fin n) :
    lb1X p (Fin.castAdd n k) = p.X k := by unfold lb1X; rw [Fin.addCases_left]

@[simp] theorem lb1X_addNat (p : Pauli n) (k : Fin n) :
    lb1X p (k.addNat n) = 0 := by
  rw [← Fin.natAdd_eq_addNat]; unfold lb1X; rw [Fin.addCases_right]

@[simp] theorem lb1Z_castAdd (p : Pauli n) (k : Fin n) :
    lb1Z p (Fin.castAdd n k) = p.Z k := by unfold lb1Z; rw [Fin.addCases_left]

@[simp] theorem lb1Z_addNat (p : Pauli n) (k : Fin n) :
    lb1Z p (k.addNat n) = 0 := by
  rw [← Fin.natAdd_eq_addNat]; unfold lb1Z; rw [Fin.addCases_right]

@[simp] theorem lb2X_castAdd (p : Pauli n) (k : Fin n) :
    lb2X p (Fin.castAdd n k) = 0 := by unfold lb2X; rw [Fin.addCases_left]

@[simp] theorem lb2X_addNat (p : Pauli n) (k : Fin n) :
    lb2X p (k.addNat n) = p.X k := by
  rw [← Fin.natAdd_eq_addNat]; unfold lb2X; rw [Fin.addCases_right]

@[simp] theorem lb2Z_castAdd (p : Pauli n) (k : Fin n) :
    lb2Z p (Fin.castAdd n k) = 0 := by unfold lb2Z; rw [Fin.addCases_left]

@[simp] theorem lb2Z_addNat (p : Pauli n) (k : Fin n) :
    lb2Z p (k.addNat n) = p.Z k := by
  rw [← Fin.natAdd_eq_addNat]; unfold lb2Z; rw [Fin.addCases_right]

/-- Additivity of `lb1X` (helper for the LinearMap.map_add' field). -/
private theorem lb1X_add (p q : Pauli n) : lb1X (p + q) = lb1X p + lb1X q := by
  funext i
  induction i using Fin.addCases with
  | left k => simp [X_add]
  | right k => simp

private theorem lb1Z_add (p q : Pauli n) : lb1Z (p + q) = lb1Z p + lb1Z q := by
  funext i
  induction i using Fin.addCases with
  | left k => simp [Z_add]
  | right k => simp

private theorem lb2X_add (p q : Pauli n) : lb2X (p + q) = lb2X p + lb2X q := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp [X_add]

private theorem lb2Z_add (p q : Pauli n) : lb2Z (p + q) = lb2Z p + lb2Z q := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp [Z_add]

private theorem lb1X_smul (c : ZMod 2) (p : Pauli n) : lb1X (c • p) = c • lb1X p := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp

private theorem lb1Z_smul (c : ZMod 2) (p : Pauli n) : lb1Z (c • p) = c • lb1Z p := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp

private theorem lb2X_smul (c : ZMod 2) (p : Pauli n) : lb2X (c • p) = c • lb2X p := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp

private theorem lb2Z_smul (c : ZMod 2) (p : Pauli n) : lb2Z (c • p) = c • lb2Z p := by
  funext i
  induction i using Fin.addCases with
  | left k => simp
  | right k => simp

/-- Embedding of `Pauli n` into block 1 of `Pauli (n + n)`: place the
input Pauli on the first `n` qubits, leave the second `n` qubits
trivial. -/
def liftBlock1 : Pauli n →ₗ[ZMod 2] Pauli (n + n) where
  toFun p := ⟨lb1X p, lb1Z p⟩
  map_add' p q := by
    apply Pauli.ext
    · exact lb1X_add p q
    · exact lb1Z_add p q
  map_smul' c p := by
    apply Pauli.ext
    · exact lb1X_smul c p
    · exact lb1Z_smul c p

/-- Embedding of `Pauli n` into block 2 of `Pauli (n + n)`. -/
def liftBlock2 : Pauli n →ₗ[ZMod 2] Pauli (n + n) where
  toFun p := ⟨lb2X p, lb2Z p⟩
  map_add' p q := by
    apply Pauli.ext
    · exact lb2X_add p q
    · exact lb2Z_add p q
  map_smul' c p := by
    apply Pauli.ext
    · exact lb2X_smul c p
    · exact lb2Z_smul c p

@[simp] theorem liftBlock1_X (p : Pauli n) : (liftBlock1 p).X = lb1X p := rfl
@[simp] theorem liftBlock1_Z (p : Pauli n) : (liftBlock1 p).Z = lb1Z p := rfl
@[simp] theorem liftBlock2_X (p : Pauli n) : (liftBlock2 p).X = lb2X p := rfl
@[simp] theorem liftBlock2_Z (p : Pauli n) : (liftBlock2 p).Z = lb2Z p := rfl

/-! ## Joint CSS stabilizer -/

/-- The joint two-copy CSS stabilizer subspace in `Pauli (n + n)`:
the sum of `liftBlock1`-image and `liftBlock2`-image of the
single-block CSS stabilizer. -/
def jointCSSStabilizer
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) :
    Submodule (ZMod 2) (Pauli (n + n)) :=
  (cssStabilizer H_X H_Z).map liftBlock1 ⊔ (cssStabilizer H_X H_Z).map liftBlock2

/-! ## Action of transversal CNOT on lifted CSS generators -/

/-- `tcnot (lift1 ⟨v, 0⟩) = lift1 ⟨v, 0⟩ + lift2 ⟨v, 0⟩`. X-control
propagates from block 1 to block 2. -/
private theorem tcnot_lb1_X_eq (v : Fin n → ZMod 2) :
    (transversalCNOT n) (liftBlock1 ⟨v, 0⟩) =
      liftBlock1 ⟨v, 0⟩ + liftBlock2 ⟨v, 0⟩ := by
  apply Pauli.ext
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp

/-- `tcnot (lift2 ⟨v, 0⟩) = lift2 ⟨v, 0⟩`. X-target on block 2 unchanged. -/
private theorem tcnot_lb2_X_eq (v : Fin n → ZMod 2) :
    (transversalCNOT n) (liftBlock2 ⟨v, 0⟩) = liftBlock2 ⟨v, 0⟩ := by
  apply Pauli.ext
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp

/-- `tcnot (lift1 ⟨0, v⟩) = lift1 ⟨0, v⟩`. Z-control on block 1 unchanged. -/
private theorem tcnot_lb1_Z_eq (v : Fin n → ZMod 2) :
    (transversalCNOT n) (liftBlock1 ⟨0, v⟩) = liftBlock1 ⟨0, v⟩ := by
  apply Pauli.ext
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp

/-- `tcnot (lift2 ⟨0, v⟩) = lift1 ⟨0, v⟩ + lift2 ⟨0, v⟩`. Z-target
propagates from block 2 to block 1. -/
private theorem tcnot_lb2_Z_eq (v : Fin n → ZMod 2) :
    (transversalCNOT n) (liftBlock2 ⟨0, v⟩) =
      liftBlock1 ⟨0, v⟩ + liftBlock2 ⟨0, v⟩ := by
  apply Pauli.ext
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp
  · funext i
    induction i using Fin.addCases with
    | left k => simp
    | right k => simp

/-! ## Stabilizer preservation -/

/-- Auxiliary: the X-generator block-1 lift, transversal CNOT image, is
in the joint stabilizer. -/
private theorem tcnot_lb1_cssXGen_mem
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (i : Fin r_X) :
    (transversalCNOT n) (liftBlock1 (cssXGen H_X i)) ∈
      jointCSSStabilizer H_X H_Z := by
  unfold cssXGen
  rw [tcnot_lb1_X_eq]
  refine Submodule.add_mem _ ?_ ?_
  · apply Submodule.mem_sup_left
    refine ⟨⟨H_X i, 0⟩, ?_, rfl⟩
    apply Submodule.mem_sup_left
    exact Submodule.subset_span ⟨i, rfl⟩
  · apply Submodule.mem_sup_right
    refine ⟨⟨H_X i, 0⟩, ?_, rfl⟩
    apply Submodule.mem_sup_left
    exact Submodule.subset_span ⟨i, rfl⟩

private theorem tcnot_lb1_cssZGen_mem
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (j : Fin r_Z) :
    (transversalCNOT n) (liftBlock1 (cssZGen H_Z j)) ∈
      jointCSSStabilizer H_X H_Z := by
  unfold cssZGen
  rw [tcnot_lb1_Z_eq]
  apply Submodule.mem_sup_left
  refine ⟨⟨0, H_Z j⟩, ?_, rfl⟩
  apply Submodule.mem_sup_right
  exact Submodule.subset_span ⟨j, rfl⟩

private theorem tcnot_lb2_cssXGen_mem
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (i : Fin r_X) :
    (transversalCNOT n) (liftBlock2 (cssXGen H_X i)) ∈
      jointCSSStabilizer H_X H_Z := by
  unfold cssXGen
  rw [tcnot_lb2_X_eq]
  apply Submodule.mem_sup_right
  refine ⟨⟨H_X i, 0⟩, ?_, rfl⟩
  apply Submodule.mem_sup_left
  exact Submodule.subset_span ⟨i, rfl⟩

private theorem tcnot_lb2_cssZGen_mem
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (j : Fin r_Z) :
    (transversalCNOT n) (liftBlock2 (cssZGen H_Z j)) ∈
      jointCSSStabilizer H_X H_Z := by
  unfold cssZGen
  rw [tcnot_lb2_Z_eq]
  refine Submodule.add_mem _ ?_ ?_
  · apply Submodule.mem_sup_left
    refine ⟨⟨0, H_Z j⟩, ?_, rfl⟩
    apply Submodule.mem_sup_right
    exact Submodule.subset_span ⟨j, rfl⟩
  · apply Submodule.mem_sup_right
    refine ⟨⟨0, H_Z j⟩, ?_, rfl⟩
    apply Submodule.mem_sup_right
    exact Submodule.subset_span ⟨j, rfl⟩

/-- Forward inclusion: transversal CNOT maps the joint CSS stabilizer
into itself. -/
private theorem transversalCNOT_jointCSSStabilizer_le
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) :
    (jointCSSStabilizer H_X H_Z).map (transversalCNOT n).toLinearMap ≤
      jointCSSStabilizer H_X H_Z := by
  unfold jointCSSStabilizer
  rw [Submodule.map_sup]
  refine sup_le ?_ ?_
  · -- (cssStab.map liftBlock1).map tcnot ⊆ joint
    rw [← Submodule.map_comp]
    rw [Submodule.map_le_iff_le_comap]
    -- Need: cssStabilizer H_X H_Z ⊆ comap (liftBlock1 ≫ tcnot) (jointCSSStabilizer)
    unfold cssStabilizer
    refine sup_le ?_ ?_
    · unfold cssXStabilizer
      rw [Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      exact tcnot_lb1_cssXGen_mem H_X H_Z i
    · unfold cssZStabilizer
      rw [Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      exact tcnot_lb1_cssZGen_mem H_X H_Z j
  · rw [← Submodule.map_comp]
    rw [Submodule.map_le_iff_le_comap]
    unfold cssStabilizer
    refine sup_le ?_ ?_
    · unfold cssXStabilizer
      rw [Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      exact tcnot_lb2_cssXGen_mem H_X H_Z i
    · unfold cssZStabilizer
      rw [Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      exact tcnot_lb2_cssZGen_mem H_X H_Z j

/-- **Transversal CNOT preserves the joint CSS stabilizer.** This is
the algebraic core of "transversal CNOT implements logical CNOT on CSS
codes". The four lifted generator types map to:

  * `X-block 1 ↦ X-block 1 + X-block 2`
  * `X-block 2 ↦ X-block 2`
  * `Z-block 1 ↦ Z-block 1`
  * `Z-block 2 ↦ Z-block 1 + Z-block 2`

all of which lie in the joint stabilizer. By linearity the whole joint
stabilizer maps into itself; transversal CNOT is its own inverse, so the
inclusion is an equality. -/
theorem transversalCNOT_preserves_jointCSSStabilizer
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) :
    (jointCSSStabilizer H_X H_Z).map (transversalCNOT n).toLinearMap =
      jointCSSStabilizer H_X H_Z := by
  apply le_antisymm
  · exact transversalCNOT_jointCSSStabilizer_le H_X H_Z
  · intro p hp
    refine ⟨(transversalCNOT n).symm p, ?_, by simp⟩
    have hself : (transversalCNOT n).symm p = (transversalCNOT n) p := rfl
    rw [hself]
    exact transversalCNOT_jointCSSStabilizer_le H_X H_Z ⟨p, hp, rfl⟩

end FTQCLib.Codes
