/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Gates.CliffordGateGeneration
import FTQCLib.Hilbert.AffineSymplectic

/-!
# Transvections generate the symplectic group on `Pauli n`

Specialization of the abstract Cartan–Dieudonné theorem `transvections_generate_sp` to the concrete
symplectic space `(Pauli n, omega)`: the symplectic transvections generate
`Sp(2n, 𝔽₂) = spSubgroup n`.

This is the symplectic-geometry core of the surjectivity of `Φ`: the realized symplectic group is
generated by transvections. Combined with the fact that each transvection is a Clifford-gate word,
it discharges `SpGeneratedByCliffordGates` (`spGeneratedByCliffordGates`), the generation
hypothesis of the surjectivity argument. -/

namespace FTQCLib.Hilbert

open FTQCLib.Pauli FTQCLib.Gates

variable {n : ℕ}


/-- Since `SpGeneratedByCliffordGates` holds (`spGeneratedByCliffordGates`), surjectivity of `Φ`
reduces to `hmem` — the Hilbert-side gate lifts (every elementary gate lies in `range Φ`), proved
as `cliffordGateGens_subset_range`. -/
theorem surjective_cliffordToSp_of_gateLifts
    (hmem : cliffordGateGens n ⊆ (cliffordToSp (n := n)).range) :
    Function.Surjective (cliffordToSp (n := n)) :=
  surjective_cliffordToSp_of_generation hmem (spGeneratedByCliffordGates n)

/-- **The Clifford lift of `Sp(V)`, from the gate lifts.** Given the gate lifts (`hmem`), every
symplectic automorphism lifts to a Clifford unitary. The symplectic-generation half is
unconditional. -/
theorem cliffordSymplecticLift_of_gateLifts
    (hmem : cliffordGateGens n ⊆ (cliffordToSp (n := n)).range) :
    CliffordSymplecticLift n :=
  cliffordSymplecticLift_of_generation hmem (spGeneratedByCliffordGates n)

end FTQCLib.Hilbert
