/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Pauli.Basis
import FTQCLib.Stabilizer.Defs
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.ToLin

set_option linter.unusedSectionVars false

/-! # CSS codes from parity-check matrices

A \emph{CSS code} on `n` qubits is specified by two binary matrices

    H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)
    H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)

satisfying the \emph{CSS commutativity condition}

    H_X · H_Zᵀ = 0.

This file defines:

* **C1 (CSS definition)** `IsCSSPair` — the commutativity predicate on
  a pair of check matrices.
* **C2 (stabilizer subspace)** `cssXStabilizer`, `cssZStabilizer`,
  `cssStabilizer` — the stabilizer subspaces generated by X-type
  and Z-type rows. The full CSS stabilizer is their sum.
* **C2 (commutativity)** `cssStabilizer_isStabilizer` — under the CSS
  commutativity condition the joint subspace is `ω`-isotropic.

C3 (dimension/rank) and C4–C5 (X/Z-logical spaces) live in
`FTQCLib.CSS.Logical`.
-/

namespace FTQCLib.CSS

open FTQCLib.Pauli FTQCLib.Stabilizer Matrix

variable {n r_X r_Z : ℕ}

/-- The CSS commutativity condition: `H_X · H_Zᵀ = 0`. Equivalently
the rows of `H_X` and `H_Z` are pairwise orthogonal as vectors in
`(ZMod 2)^n`. -/
def IsCSSPair (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) : Prop :=
  H_X * H_Zᵀ = 0

/-- The X-type stabilizer generator from row `i` of `H_X`: a pure
`X`-Pauli with support equal to that row. -/
def cssXGen (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)) (i : Fin r_X) :
    Pauli n :=
  ⟨H_X i, 0⟩

/-- The Z-type stabilizer generator from row `i` of `H_Z`: a pure
`Z`-Pauli with support equal to that row. -/
def cssZGen (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (i : Fin r_Z) :
    Pauli n :=
  ⟨0, H_Z i⟩

/-- The X-type stabilizer subspace: the `(ZMod 2)`-span of the X-type
generators `cssXGen H_X i` over all rows `i` of `H_X`. -/
def cssXStabilizer (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)) :
    Submodule (ZMod 2) (Pauli n) :=
  Submodule.span (ZMod 2) (Set.range (cssXGen H_X))

/-- The Z-type stabilizer subspace: the `(ZMod 2)`-span of the Z-type
generators `cssZGen H_Z i` over all rows `i` of `H_Z`. -/
def cssZStabilizer (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) :
    Submodule (ZMod 2) (Pauli n) :=
  Submodule.span (ZMod 2) (Set.range (cssZGen H_Z))

/-- The full CSS stabilizer subspace: the join of the X-type and
Z-type subspaces. -/
def cssStabilizer (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) :
    Submodule (ZMod 2) (Pauli n) :=
  cssXStabilizer H_X ⊔ cssZStabilizer H_Z

/-- `ω` between an X-type generator and a Z-type generator equals the
`(i, j)`-entry of `H_X · H_Zᵀ`. -/
theorem omega_cssXGen_cssZGen
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2))
    (i : Fin r_X) (j : Fin r_Z) :
    omega (cssXGen H_X i) (cssZGen H_Z j) = (H_X * H_Zᵀ) i j := by
  simp [omega, cssXGen, cssZGen, Matrix.mul_apply, Matrix.transpose_apply]

/-- Two X-type generators always `ω`-commute (their `ω` is zero). -/
@[simp]
theorem omega_cssXGen_cssXGen
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)) (i j : Fin r_X) :
    omega (cssXGen H_X i) (cssXGen H_X j) = 0 := by
  simp [omega, cssXGen]

/-- Two Z-type generators always `ω`-commute. -/
@[simp]
theorem omega_cssZGen_cssZGen
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)) (i j : Fin r_Z) :
    omega (cssZGen H_Z i) (cssZGen H_Z j) = 0 := by
  simp [omega, cssZGen]

/-- Under the CSS commutativity condition, all X-type and Z-type
generators pairwise `ω`-commute. -/
theorem omega_cssXGen_cssZGen_of_isCSSPair
    {H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)}
    {H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)} (h : IsCSSPair H_X H_Z)
    (i : Fin r_X) (j : Fin r_Z) :
    omega (cssXGen H_X i) (cssZGen H_Z j) = 0 := by
  rw [omega_cssXGen_cssZGen, h]
  rfl

/-- `ω` vanishes on the `cssXStabilizer × cssXStabilizer` block: X-type
generators pairwise commute, so by bilinearity the whole span does too. -/
theorem omega_eq_zero_of_cssXStabilizer
    (H_X : Matrix (Fin r_X) (Fin n) (ZMod 2))
    {a b : Pauli n} (ha : a ∈ cssXStabilizer H_X)
    (hb : b ∈ cssXStabilizer H_X) : omega a b = 0 := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ ha
  · rintro x ⟨i, rfl⟩
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hb
    · rintro y ⟨j, rfl⟩; simp
    · simp
    · intros y z _ _ hy hz; rw [omega_add_right, hy, hz, zero_add]
    · intros c y _ hy; rw [omega_smul_right, hy, mul_zero]
  · simp
  · intros x y _ _ hx hy; rw [omega_add_left, hx, hy, zero_add]
  · intros c x _ hx; rw [omega_smul_left, hx, mul_zero]

/-- `ω` vanishes on the `cssZStabilizer × cssZStabilizer` block. -/
theorem omega_eq_zero_of_cssZStabilizer
    (H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2))
    {a b : Pauli n} (ha : a ∈ cssZStabilizer H_Z)
    (hb : b ∈ cssZStabilizer H_Z) : omega a b = 0 := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ ha
  · rintro x ⟨i, rfl⟩
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hb
    · rintro y ⟨j, rfl⟩; simp
    · simp
    · intros y z _ _ hy hz; rw [omega_add_right, hy, hz, zero_add]
    · intros c y _ hy; rw [omega_smul_right, hy, mul_zero]
  · simp
  · intros x y _ _ hx hy; rw [omega_add_left, hx, hy, zero_add]
  · intros c x _ hx; rw [omega_smul_left, hx, mul_zero]

/-- `ω` vanishes on the `cssXStabilizer × cssZStabilizer` block under
the CSS commutativity condition. -/
theorem omega_eq_zero_of_cssXZStabilizer
    {H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)}
    {H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)} (hCSS : IsCSSPair H_X H_Z)
    {a b : Pauli n} (ha : a ∈ cssXStabilizer H_X)
    (hb : b ∈ cssZStabilizer H_Z) : omega a b = 0 := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ ha
  · rintro x ⟨i, rfl⟩
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hb
    · rintro y ⟨j, rfl⟩
      exact omega_cssXGen_cssZGen_of_isCSSPair hCSS i j
    · simp
    · intros y z _ _ hy hz; rw [omega_add_right, hy, hz, zero_add]
    · intros c y _ hy; rw [omega_smul_right, hy, mul_zero]
  · simp
  · intros x y _ _ hx hy; rw [omega_add_left, hx, hy, zero_add]
  · intros c x _ hx; rw [omega_smul_left, hx, mul_zero]

/-- **C2 (isotropy):** under the CSS commutativity condition, the full
CSS stabilizer subspace is `ω`-isotropic, hence a stabilizer subspace
in the sense of `IsStabilizer`. -/
theorem cssStabilizer_isStabilizer
    {H_X : Matrix (Fin r_X) (Fin n) (ZMod 2)}
    {H_Z : Matrix (Fin r_Z) (Fin n) (ZMod 2)} (h : IsCSSPair H_X H_Z) :
    IsStabilizer (cssStabilizer H_X H_Z) := by
  intro p hp q hq
  rw [cssStabilizer, Submodule.mem_sup] at hp hq
  obtain ⟨pX, hpX, pZ, hpZ, rfl⟩ := hp
  obtain ⟨qX, hqX, qZ, hqZ, rfl⟩ := hq
  rw [omega_add_left, omega_add_right, omega_add_right]
  rw [omega_eq_zero_of_cssXStabilizer H_X hpX hqX,
      omega_eq_zero_of_cssXZStabilizer h hpX hqZ]
  rw [show omega pZ qX = 0 from by
        rw [omega_comm]; exact omega_eq_zero_of_cssXZStabilizer h hqX hpZ,
      omega_eq_zero_of_cssZStabilizer H_Z hpZ hqZ]
  ring

end FTQCLib.CSS
