/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/

/-!
# Elimination order search data

Generated by `tools/search/elimination_order.py --lean` (step T04.2). Holds the cases, from a
canonical-order-capped search over `n ≤ 3`, `h ∈ {2, 3}`, `m ≤ 3`, where two maximal
elimination sequences (`docs/framing/T04.md`) from the same carrier state disagree, either by
reach (final heights differ) or by the support/phase invariant of the Criterion section.

Never edit by hand; regenerate with `python3 tools/search/elimination_order.py --lean` and
save the output verbatim (`docs/search/T04.json` holds the JSON twin, with the same cases and
the counts this docstring omits). The generator's search space is a canonical-order cap, not
the full family of `docs/framing/T04.md`'s table — see that script's own docstring for why and
for the exact enumeration order. Each cell's JSON record carries `total_admissible` beside
`examined`; a cell with `examined < total_admissible` is not a closed scope (CODE-STYLE 7.3).
-/

namespace FTQCLib.Carrier.EliminationOrderData

/-- One exponent's nonzero coefficient: an index into that cell's admissible-monomial list
(`tools/search/elimination_order.py`'s `admissible_monomials`, size then lexicographic order)
and its value mod `2 ^ m`. -/
structure Coeff where
  monomialIndex : Nat
  value : Nat
  deriving Repr, DecidableEq

/-- One elimination step: the bound-bit index eliminated, the move (`0` collapse, `1`/`2`
rotate with the search's smaller/larger valid `a`), and whether the chosen bit read the
remaining bound word. -/
structure Step where
  boundIndex : Nat
  move : Nat
  readsOtherBoundBits : Bool
  deriving Repr, DecidableEq

/-- One disagreement case: the cell, the exponent as its nonzero coefficients, and the two
maximal sequences with their final heights. `byReach` is `true` when the heights differ
(the Criterion section's preferred certificate); `false` means the invariant certificate. -/
structure Case where
  n : Nat
  h : Nat
  m : Nat
  coeffs : List Coeff
  sequenceA : List Step
  heightA : Nat
  sequenceB : List Step
  heightB : Nat
  byReach : Bool
  deriving Repr, DecidableEq

/-- The cases this run's search found, in cell order (`n`, then `h`, then `m`) and within a
cell in the search's canonical enumeration order. -/
def cases : List Case := [
  ⟨0, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨6, 2⟩], [⟨0, 1, true⟩], 2, [⟨1, 1, true⟩], 2, false⟩,
  ⟨0, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨6, 2⟩], [⟨0, 1, true⟩], 2, [⟨1, 1, true⟩], 2, false⟩,
  ⟨0, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨6, 2⟩], [⟨0, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨0, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨6, 2⟩], [⟨0, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨0, 3, 2, [⟨1, 1⟩, ⟨2, 3⟩, ⟨6, 2⟩], [⟨1, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨0, 3, 2, [⟨1, 3⟩, ⟨2, 1⟩, ⟨6, 2⟩], [⟨1, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨0, 3, 3, [⟨0, 2⟩, ⟨1, 6⟩, ⟨6, 4⟩], [⟨0, 1, true⟩], 2, [⟨1, 1, true⟩], 2, false⟩,
  ⟨0, 3, 3, [⟨0, 6⟩, ⟨1, 2⟩, ⟨6, 4⟩], [⟨0, 1, true⟩], 2, [⟨1, 1, true⟩], 2, false⟩,
  ⟨0, 3, 3, [⟨0, 2⟩, ⟨2, 6⟩, ⟨6, 4⟩], [⟨0, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨1, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨5, 2⟩], [⟨1, 1, true⟩], 1, [⟨2, 1, true⟩], 1, false⟩,
  ⟨1, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨5, 2⟩], [⟨1, 1, true⟩], 1, [⟨2, 1, true⟩], 1, false⟩,
  ⟨1, 2, 3, [⟨0, 2⟩, ⟨1, 6⟩, ⟨5, 4⟩], [⟨1, 1, true⟩], 1, [⟨2, 1, true⟩], 1, false⟩,
  ⟨1, 2, 3, [⟨0, 6⟩, ⟨1, 2⟩, ⟨5, 4⟩], [⟨1, 1, true⟩], 1, [⟨2, 1, true⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨9, 2⟩], [⟨1, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨9, 2⟩], [⟨1, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨12, 2⟩], [⟨1, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨1, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨12, 2⟩], [⟨1, 1, true⟩], 2, [⟨2, 1, true⟩], 2, false⟩,
  ⟨1, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨10, 2⟩], [⟨1, 1, true⟩, ⟨2, 0, false⟩], 1, [⟨2, 0, false⟩, ⟨3, 1, true⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨10, 2⟩], [⟨1, 1, true⟩, ⟨2, 0, false⟩], 1, [⟨2, 0, false⟩, ⟨3, 1, true⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨12, 2⟩], [⟨1, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨1, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨12, 2⟩], [⟨1, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨1, 3, 2, [⟨1, 1⟩, ⟨2, 3⟩, ⟨11, 2⟩], [⟨1, 0, false⟩, ⟨2, 1, true⟩], 1, [⟨1, 0, false⟩, ⟨3, 1, true⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨1, 3⟩, ⟨2, 1⟩, ⟨11, 2⟩], [⟨1, 0, false⟩, ⟨2, 1, true⟩], 1, [⟨1, 0, false⟩, ⟨3, 1, true⟩], 1, false⟩,
  ⟨1, 3, 2, [⟨1, 1⟩, ⟨2, 3⟩, ⟨12, 2⟩], [⟨2, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨1, 3, 2, [⟨1, 3⟩, ⟨2, 1⟩, ⟨12, 2⟩], [⟨2, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨2, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨9, 2⟩], [⟨2, 1, true⟩], 1, [⟨3, 1, true⟩], 1, false⟩,
  ⟨2, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨9, 2⟩], [⟨2, 1, true⟩], 1, [⟨3, 1, true⟩], 1, false⟩,
  ⟨2, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨10, 2⟩], [⟨2, 1, true⟩], 1, [⟨3, 1, true⟩], 1, false⟩,
  ⟨2, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨10, 2⟩], [⟨2, 1, true⟩], 1, [⟨3, 1, true⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨15, 2⟩], [⟨2, 1, true⟩, ⟨4, 0, false⟩], 1, [⟨3, 1, true⟩, ⟨4, 0, false⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨15, 2⟩], [⟨2, 1, true⟩, ⟨4, 0, false⟩], 1, [⟨3, 1, true⟩, ⟨4, 0, false⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨18, 2⟩], [⟨2, 1, true⟩, ⟨4, 0, false⟩], 1, [⟨3, 1, true⟩, ⟨4, 0, false⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨18, 2⟩], [⟨2, 1, true⟩, ⟨4, 0, false⟩], 1, [⟨3, 1, true⟩, ⟨4, 0, false⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨21, 2⟩], [⟨2, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨21, 2⟩], [⟨2, 1, true⟩], 2, [⟨3, 1, true⟩], 2, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨16, 2⟩], [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨3, 0, false⟩, ⟨4, 1, true⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨16, 2⟩], [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨3, 0, false⟩, ⟨4, 1, true⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨19, 2⟩], [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨3, 0, false⟩, ⟨4, 1, true⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨19, 2⟩], [⟨2, 1, true⟩, ⟨3, 0, false⟩], 1, [⟨3, 0, false⟩, ⟨4, 1, true⟩], 1, false⟩,
  ⟨2, 3, 2, [⟨0, 1⟩, ⟨2, 3⟩, ⟨21, 2⟩], [⟨2, 1, true⟩], 2, [⟨4, 1, true⟩], 2, false⟩,
  ⟨2, 3, 2, [⟨0, 3⟩, ⟨2, 1⟩, ⟨21, 2⟩], [⟨2, 1, true⟩], 2, [⟨4, 1, true⟩], 2, false⟩,
  ⟨3, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨13, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩,
  ⟨3, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨13, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩,
  ⟨3, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨16, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩,
  ⟨3, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨16, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩,
  ⟨3, 2, 2, [⟨0, 1⟩, ⟨1, 3⟩, ⟨17, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩,
  ⟨3, 2, 2, [⟨0, 3⟩, ⟨1, 1⟩, ⟨17, 2⟩], [⟨3, 1, true⟩], 1, [⟨4, 1, true⟩], 1, false⟩
]

end FTQCLib.Carrier.EliminationOrderData
