/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import ECCLib.Scheme.OrbitalSpectrum
import ECCLib.Scheme.Spectrum
import ECCLib.Scheme.DualAction

/-!
# The translation scheme as an orbital algebra

The relationship between the general orbital layer and the translation scheme of
`Scheme/Translation.lean`. Subsumption holds at the level of objects and dimension and fails at
the level of commutativity and positivity; this file proves the part that holds and states
precisely where it fails.

## Main results

* `schemeAlgebra_eq_permCommutant` — the translation-scheme algebra **is** a commutant of a set of
  permutations, by `rfl` after two `Set` rewrites.
* `orbital_iff_sub` — orbitals of translations-with-`H` correspond to `H`-orbits of differences.
* `orbProjBasis` — **the translation-scheme dual-orbit idempotents are a basis of the
  translation-scheme algebra.**

## Layer by layer, what is true

**Objects and dimension — TRUE, and the subsumption is genuine.** `schemeAlgebra H V` is
definitionally a `permCommutant`, and with `mem_permCommutant_closure_iff` the commutant of the
generating set is the commutant of the group it generates. No semidirect product is ever built.
`orbital_iff_sub` then explains why the translation-scheme dimension came out as an *orbit* count
rather than an *orbital* count: translations collapse the orbitals of `V × V` onto `V` along
`y − x`.

**Commutativity — FALSE as subsumption.** `schemeAlgebra_mul_comm` comes from
`Matrix.circulant_mul_comm` — translation-invariance — and holds for **every** `H`. The general
layer's commutativity comes from self-pairing, and self-pairing fails at legitimate translation
schemes: the regular action of a group of odd order is not self-paired, compiled in
`Scheme/OrbitalSpectrumCheck.lean`. So the two are independent sufficient conditions feeding one
interface, not one implying the other.

**The eigenmatrices — instantiable, not subsuming.** `Scheme/Spectrum.lean`'s `PQ_eq` is a
summation identity over dual orbits with a choice of representatives and *is* character
orthogonality. `eigenmatrixP_mul_eigenmatrixQ` is a change-of-basis identity. Neither implies the
other formally; the general one is broader in indexing and weaker in content.

**`Scheme/LP.lean` — NOT subsumed.**
`class_delsarte_nonneg` quantifies over an arbitrary finite character set and an arbitrary class
map with no group anywhere. A group-indexed statement cannot recover it. Where a relationship
exists it runs the other way: the orbit class map is one instantiation of LP's own `w`.

## The dividend

`orbProjBasis` is new content about the translation-scheme objects, obtained on the way to
a general theory rather than from it. It reaches the idempotent identification by **recognition** —
linear independence plus cardinality — so it needs no uniqueness-up-to-permutation theorem, which
Mathlib does not have. That theorem is `exists_equiv_primitiveIdempotent`
(`ECCLib/SplitAlgebra.lean`), used by `Scheme/TranslationSpectrum.lean`; nothing here depends
on it.
-/

namespace ECCLib.Scheme

open Finset Matrix MulAction
open scoped ECCLib.Scheme

section Bridge

variable {V : Type*} [AddCommGroup V] [Fintype V] [DecidableEq V]
variable {H : Type*} [Group H] [Fintype H] [DistribMulAction H V]

omit [Fintype H] in
/-- **The translation-scheme algebra IS a permutation-set commutant.** No new definition,
no semidirect product — the two `Set`s of generators are literally the translations and the
`H`-action. -/
theorem schemeAlgebra_eq_permCommutant :
    schemeAlgebra H V
      = permCommutant ℂ (Set.range (fun g : V => Equiv.addRight g)
          ∪ Set.range (fun h : H => MulAction.toPerm h (β := V))) := by
  rw [schemeAlgebra, permCommutant, permMats, Set.image_union, transMats, actMats,
    ← Set.range_comp, ← Set.range_comp]
  rfl

omit [Fintype V] [DecidableEq V] [Fintype H] in
/-- **Orbitals collapse to orbits of differences.** Two ordered pairs lie in the same orbital of
"translations together with `H`" exactly when their differences lie in the same `H`-orbit. This
is what makes the translation-scheme dimension theorem an orbit count, and it needs no `V ⋊ H`. -/
theorem orbital_iff_sub (x y x' y' : V) :
    (∃ (h : H) (t : V), x' = h • x + t ∧ y' = h • y + t)
      ↔ ∃ h : H, y' - x' = h • (y - x) := by
  constructor
  · rintro ⟨h, t, rfl, rfl⟩
    exact ⟨h, by rw [add_sub_add_right_eq_sub, smul_sub]⟩
  · rintro ⟨h, hd⟩
    refine ⟨h, x' - h • x, by abel, ?_⟩
    have hy : y' = (y' - x') + x' := by abel
    rw [hy, hd, smul_sub]
    abel

/-! ## Dimension: the subsumption is genuine, and here it is proved

The translation-scheme algebra is not merely *like* an orbital algebra — it **is** one, for the
group generated by the translations together with the `H`-action. So the translation-scheme
dimension theorem is recoverable from the general one, and comparing the two routes yields a
combinatorial identity that neither proves on its own. -/

/-- The group generated by the translations of `V` together with the `H`-action. -/
def permGroup (H : Type*) [Group H] (V : Type*) [AddCommGroup V] [DistribMulAction H V] :
    Subgroup (Equiv.Perm V) :=
  Subgroup.closure (Set.range (fun g : V => Equiv.addRight g)
    ∪ Set.range (fun h : H => MulAction.toPerm h (β := V)))

omit [AddCommGroup V] [Fintype V] [DecidableEq V] in
/-- A subgroup of `Equiv.Perm V`, viewed as an acting group, has exactly that subgroup as its
set of permutations. -/
theorem actPerms_subgroup (K : Subgroup (Equiv.Perm V)) :
    actPerms ↥K V = (K : Set (Equiv.Perm V)) := by
  ext σ
  exact ⟨fun ⟨g, hg⟩ => hg ▸ g.2, fun hσ => ⟨⟨σ, hσ⟩, rfl⟩⟩

omit [AddCommGroup V] in
/-- The commutant of a set is the commutant of the group it generates, as subalgebras. -/
theorem permCommutant_closure (S : Set (Equiv.Perm V)) :
    permCommutant ℂ S = permCommutant ℂ (Subgroup.closure S : Set (Equiv.Perm V)) :=
  SetLike.ext fun M => mem_permCommutant_closure_iff M

noncomputable instance : Fintype ↥(permGroup H V) := Fintype.ofFinite _

omit [AddCommGroup V] in
theorem orbitalAlgebra_subgroup (K : Subgroup (Equiv.Perm V)) [Fintype ↥K] :
    orbitalAlgebra ℂ ↥K V = permCommutant ℂ (K : Set (Equiv.Perm V)) := by
  unfold orbitalAlgebra
  rw [actPerms_subgroup]

omit [Fintype H] in
/-- **The translation-scheme algebra IS an orbital algebra**, for the generated group. -/
theorem schemeAlgebra_eq_orbitalAlgebra :
    schemeAlgebra H V = orbitalAlgebra ℂ ↥(permGroup H V) V := by
  rw [orbitalAlgebra_subgroup, schemeAlgebra_eq_permCommutant, permCommutant_closure]
  rfl

omit [Fintype H] in
/-- **The translation-scheme dimension theorem, re-derived through the general layer.** -/
theorem finrank_schemeAlgebra_of_orbital :
    Module.finrank ℂ ↥(schemeAlgebra H V)
      = (orbits ↥(permGroup H V) (V × V)).card := by
  rw [schemeAlgebra_eq_orbitalAlgebra, finrank_orbitalAlgebra]

/-- **The two-route agreement.** A combinatorial identity obtained by counting one dimension two
ways: the orbitals of the generated group on `V × V` are exactly as many as the `H`-orbits on
`V`. Neither dimension theorem proves this alone. -/
theorem card_orbits_prod_eq_card_orbits :
    (orbits ↥(permGroup H V) (V × V)).card = (orbits H V).card := by
  rw [← finrank_schemeAlgebra_of_orbital, finrank_schemeAlgebra]

end Bridge

/-! ## The dividend: the translation-scheme idempotents are a basis -/

section Payback

variable {V : Type*} [AddCommGroup V] [Fintype V] [DecidableEq V]
variable {H : Type*} [Group H] [Fintype H] [DistribMulAction H V]

omit [DecidableEq V] in
/-- An orbit projector is nonzero: its diagonal entry is `|S| / |V|`. -/
theorem orbProj_ne_zero {S : Finset (AddChar V ℂ)} (hS : S.Nonempty) : orbProj S ≠ 0 := by
  intro hzero
  have hd : orbProj S 0 0 = 0 := by rw [hzero]; rfl
  rw [orbProj_eq_circulant] at hd
  simp only [Matrix.circulant_apply, sub_self, qEnt, AddChar.map_zero_eq_one,
    Finset.sum_const, nsmul_eq_mul, mul_one] at hd
  have hN : (Fintype.card V : ℂ) ≠ 0 := by exact_mod_cast Fintype.card_ne_zero
  rcases mul_eq_zero.mp hd with h | h
  · exact hN (inv_eq_zero.mp h)
  · have hc : S.card = 0 := by exact_mod_cast h
    exact absurd hc (Finset.card_ne_zero_of_mem hS.choose_spec)

/-- The dual orbit count equals the primal one, in the `Finset` index the scheme layer uses. -/
theorem card_orbits_dual_eq_card_orbits :
    (orbits H (AddChar V ℂ)).card = (orbits H V).card := by
  classical
  rw [← card_orbitRel_quotient (H := H) (W := AddChar V ℂ),
    ← card_orbitRel_quotient (H := H) (W := V)]
  exact card_orbits_dual_eq

/-- There are exactly `finrank` many dual orbits. -/
theorem card_orbits_dual_eq_finrank_schemeAlgebra :
    Fintype.card ↥(orbits H (AddChar V ℂ)) = Module.finrank ℂ ↥(schemeAlgebra H V) := by
  rw [Fintype.card_coe, finrank_schemeAlgebra (H := H) (V := V),
    card_orbits_dual_eq_card_orbits]

/-- The `orbProj` family, viewed inside the scheme algebra. -/
noncomputable def orbProjSub (S : ↥(orbits H (AddChar V ℂ))) : ↥(schemeAlgebra H V) :=
  ⟨orbProj (S : Finset (AddChar V ℂ)), orbProj_mem_schemeAlgebra S.2⟩

theorem orbProjSub_ne_zero (S : ↥(orbits H (AddChar V ℂ))) :
    orbProjSub (H := H) (V := V) S ≠ 0 := by
  intro h
  exact orbProj_ne_zero (nonempty_of_mem_orbits S.2) (congrArg Subtype.val h)

theorem orthogonalIdempotents_orbProjSub :
    OrthogonalIdempotents (orbProjSub (H := H) (V := V)) := by
  have hinj : Function.Injective ⇑((schemeAlgebra H V).val.toRingHom) := Subtype.val_injective
  rw [← OrthogonalIdempotents.map_injective_iff ((schemeAlgebra H V).val.toRingHom) hinj]
  exact (completeOrthogonalIdempotents_orbProj (H := H) (V := V)).toOrthogonalIdempotents

theorem linearIndependent_orbProjSub :
    LinearIndependent ℂ (orbProjSub (H := H) (V := V)) :=
  linearIndependent_of_orthogonalIdempotents orthogonalIdempotents_orbProjSub
    orbProjSub_ne_zero

/-- **The `orbProj` family IS a basis of the translation-scheme algebra**, hence the primitive
idempotents. Reached by recognition — independence plus cardinality — so no
uniqueness-up-to-permutation theorem is needed. -/
noncomputable def orbProjBasis :
    Module.Basis ↥(orbits H (AddChar V ℂ)) ℂ ↥(schemeAlgebra H V) :=
  haveI : Nonempty ↥(orbits H (AddChar V ℂ)) :=
    ⟨⟨orb H (0 : AddChar V ℂ), orb_mem_orbits _⟩⟩
  basisOfLinearIndependentOfCardEqFinrank
    linearIndependent_orbProjSub card_orbits_dual_eq_finrank_schemeAlgebra

end Payback

end ECCLib.Scheme
