/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Explore.LieClosure

set_option linter.style.longLine false

/-! # The factorization's homology (cohomological/factorization framing)

The object is the factorization `D(D+2) = 0` (`FTQCLib/Frame/CurvatureObstruction.lean`); its first
candidate invariant is the pair of two-periodic quotients `ker D / im(D+2)` and `ker(D+2) / im D`.
The dictionary of `FTQCLib.Explore.LieClosure` (`D = T − 1`, `T² = 1`) identifies what these are:
`D + 2 = T + 1` is the **norm element** of the ℤ/2-action generated by the shift `T = shiftOp`, so
the two-periodic pair is the classical **Tate complex** of the shift action [standard terminology;
the identification is definitional given `T² = 1`]. Results:

* **Two-periodicity** (`funcDerivG_normOp`, `normOp_funcDerivG`): `D ∘ N = 0` and `N ∘ D = 0` — the
  operator factorization `(T−1)(T+1) = T² − 1 = 0` in both orders.
* **Global exactness at every rung and every `n`** (`exists_normOp_of_deriv_zero`,
  `exists_deriv_of_normOp_zero`): both Tate quotients vanish on the full phase module, with
  **explicit hyperplane-section witnesses** (restrict to the representative `v_i = 0` of each shift
  orbit) — constructive, general codomain, no `decide`. Structural reason: the shift action on `𝔽₂ⁿ`
  is *free* (`v ≠ v + e_i`), and free actions have vanishing Tate cohomology; the witnesses realize
  this by hand.
* **The invariant is genuinely relative/filtered** (`normOp_constFn`, `constants_relative_class`):
  on the *constants* sector the shift acts trivially and `N c = 2c`, so the within-sector equation
  is `2g = c` — unsolvable for `c = 1` over `ℤ/4`. The constant `1` is `D`-closed with **no constant
  `N`-preimage**, though a global (non-constant) one exists by exactness. The factorization carries
  no absolute invariant, but its filtration-relative invariants are nonzero.
* **The degree cost of exactness** (`witness_distinct_deriv_zero`): the global witness for a
  constant depends on a single coordinate, so differences in any two *distinct* directions kill it —
  interaction degree ≤ 1. Killing the degree-0 relative class costs exactly one interaction degree:
  the filtration sees the exactness through a degree shift of 1. This is the formalizable shadow of
  the spectral-sequence question for the filtration: the vanishing global homology *forces* the
  filtration's connecting maps to be nonzero, and the first one moves degree 0 → 1. (A full
  spectral-sequence formalization is not attempted; nothing here needs it.)

**Consequence.** The object of this framing is the Tate/norm complex of the shift action — globally
exact (no absolute homological invariant), with genuine invariants appearing exactly *relatively*,
on filtration sectors where the action degenerates (constants = the trivial-action sector; more
generally the level filtration, which the shift preserves). The framing is *filtered homological
algebra over the group algebra `A[(𝔽₂)ⁿ]`*, not absolute cohomology. An exploratory file, not part
of the `FTQCLib` target.
-/

namespace FTQCLib.Explore.FactorizationHomology

open FTQCLib.Hierarchy.BooleanMobius FTQCLib.Explore.LieClosure

variable {n : ℕ} {A : Type*} [AddCommGroup A]

/-- The **norm operator** of the shift action: `N_i = T_i + 1 = D_i + 2`. -/
def normOp (i : Fin n) (f : (Fin n → ZMod 2) → A) : (Fin n → ZMod 2) → A :=
  shiftOp i f + f

@[simp] lemma normOp_apply (i : Fin n) (f : (Fin n → ZMod 2) → A) (v : Fin n → ZMod 2) :
    normOp i f v = f (v + Pi.single i 1) + f v := rfl

/-- `N = D + 2` — the norm is the factorization's complementary factor. -/
theorem normOp_eq_funcDerivG_add_two (i : Fin n) (f : (Fin n → ZMod 2) → A) :
    normOp i f = funcDerivG i f + (2 : ℤ) • f := by
  funext v
  simp only [normOp_apply, funcDerivG_apply, Pi.add_apply, Pi.smul_apply]
  abel

private lemma two_torsion_step (i : Fin n) (v : Fin n → ZMod 2) :
    v + Pi.single i (1 : ZMod 2) + Pi.single i 1 = v := by
  rw [add_assoc, ← Pi.single_add, show (1 : ZMod 2) + 1 = 0 from by decide, Pi.single_zero,
    add_zero]

/-- **Two-periodicity, first order:** `D ∘ N = 0` (`(T−1)(T+1) = 0`). -/
theorem funcDerivG_normOp (i : Fin n) (f : (Fin n → ZMod 2) → A) :
    funcDerivG i (normOp i f) = 0 := by
  funext v
  simp only [funcDerivG_apply, normOp_apply, Pi.zero_apply, two_torsion_step]
  abel

/-- **Two-periodicity, second order:** `N ∘ D = 0` (`(T+1)(T−1) = 0`). -/
theorem normOp_funcDerivG (i : Fin n) (f : (Fin n → ZMod 2) → A) :
    normOp i (funcDerivG i f) = 0 := by
  funext v
  simp only [normOp_apply, funcDerivG_apply, Pi.zero_apply, two_torsion_step]
  abel

/-! ## Global exactness: the Tate quotients vanish on the full phase module -/

private lemma coord_shift (i : Fin n) (v : Fin n → ZMod 2) :
    (v + (Pi.single i 1 : Fin n → ZMod 2)) i = v i + 1 := by
  simp [Pi.single_eq_same]

private lemma zmod2_cases (x : ZMod 2) : x = 0 ∨ x = 1 := by revert x; decide

/-- **Exactness at `ker D`:** every shift-invariant phase is a norm. Explicit witness: restrict `f` to the
hyperplane section `v_i = 0` of the (free) shift orbits. -/
theorem exists_normOp_of_deriv_zero (i : Fin n) (f : (Fin n → ZMod 2) → A)
    (hf : funcDerivG i f = 0) :
    ∃ g : (Fin n → ZMod 2) → A, normOp i g = f := by
  have hinv : ∀ v, f (v + Pi.single i 1) = f v := fun v => by
    have h := congrFun hf v
    simp only [funcDerivG_apply, Pi.zero_apply] at h
    exact sub_eq_zero.mp h
  refine ⟨fun v => if v i = 0 then f v else 0, ?_⟩
  funext v
  simp only [normOp_apply]
  rcases zmod2_cases (v i) with hv | hv
  · rw [if_neg (by rw [coord_shift, hv]; decide), if_pos hv, zero_add]
  · rw [if_pos (by rw [coord_shift, hv]; decide), if_neg (by rw [hv]; decide), add_zero, hinv]

/-- **Exactness at `ker N`:** every shift-anti-invariant phase (`f(·+e_i) = −f`) is a difference. Explicit
witness: `−f` on the hyperplane section. -/
theorem exists_deriv_of_normOp_zero (i : Fin n) (f : (Fin n → ZMod 2) → A)
    (hf : normOp i f = 0) :
    ∃ g : (Fin n → ZMod 2) → A, funcDerivG i g = f := by
  have hanti : ∀ v, f (v + Pi.single i 1) = -f v := fun v => by
    have h := congrFun hf v
    simp only [normOp_apply, Pi.zero_apply] at h
    exact eq_neg_of_add_eq_zero_left h
  refine ⟨fun v => if v i = 0 then -f v else 0, ?_⟩
  funext v
  simp only [funcDerivG_apply]
  rcases zmod2_cases (v i) with hv | hv
  · rw [if_neg (by rw [coord_shift, hv]; decide), if_pos hv, zero_sub, neg_neg]
  · rw [if_pos (by rw [coord_shift, hv]; decide), if_neg (by rw [hv]; decide), sub_zero,
      hanti, neg_neg]

/-! ## The relative (filtered) class: nonzero on the trivial-action sector -/

/-- The constant phase. -/
def constFn (c : A) : (Fin n → ZMod 2) → A := fun _ => c

theorem funcDerivG_constFn (i : Fin n) (c : A) :
    funcDerivG i (constFn c : (Fin n → ZMod 2) → A) = 0 := by
  funext v
  simp [funcDerivG_apply, constFn]

/-- On constants the norm is doubling: `N c = 2c` — the shift acts trivially there. -/
theorem normOp_constFn (i : Fin n) (c : A) :
    normOp i (constFn c : (Fin n → ZMod 2) → A) = constFn (c + c) := by
  funext v
  simp [normOp_apply, constFn]

/-- **The relative Tate class is nonzero:** over `ℤ/4` the `D`-closed constant `1` has no *constant*
norm-preimage (`2g = 1` is unsolvable) — though a global, non-constant one exists by
`exists_normOp_of_deriv_zero`. The factorization's genuine invariants are filtration-relative. -/
theorem constants_relative_class (i : Fin n) :
    ¬ ∃ c : ZMod 4, normOp i (constFn c : (Fin n → ZMod 2) → ZMod 4) = constFn 1 := by
  rintro ⟨c, hc⟩
  have h := congrFun hc (fun _ => 0)
  simp only [normOp_apply, constFn] at h
  clear hc
  revert h
  revert c
  decide

/-- The hyperplane witness depends only on coordinate `i`: differences in any other direction kill it. -/
theorem funcDerivG_indicator_of_ne (i : Fin n) (c : A) {j : Fin n} (hji : j ≠ i) :
    funcDerivG j (fun v => if v i = 0 then c else 0) = 0 := by
  funext v
  have hcoord : (v + (Pi.single j 1 : Fin n → ZMod 2)) i = v i := by
    simp [Pi.single_eq_of_ne (Ne.symm hji)]
  simp only [funcDerivG_apply, hcoord, Pi.zero_apply, sub_self]

/-- **The degree cost of exactness:** the witness killing the constant class has interaction degree ≤ 1 — any
two distinct-direction differences annihilate it. The filtration sees the global exactness through a degree
shift of exactly one. -/
theorem witness_distinct_deriv_zero (i : Fin n) (c : A) {j k : Fin n} (hjk : j ≠ k) :
    funcDerivG j (funcDerivG k (fun v => if v i = 0 then c else 0)) = 0 := by
  rcases eq_or_ne k i with rfl | hki
  · rw [funcDerivG_comm j k, funcDerivG_indicator_of_ne k c hjk]
    funext v
    simp only [funcDerivG_apply, Pi.zero_apply, sub_self]
  · rw [funcDerivG_indicator_of_ne i c hki]
    funext v
    simp only [funcDerivG_apply, Pi.zero_apply, sub_self]

end FTQCLib.Explore.FactorizationHomology
