/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import Mathlib.Algebra.Lie.Nilpotent
import Mathlib.Algebra.Lie.OfAssociative
import FTQCLib.Frame.MetaplecticAction

set_option linter.style.longLine false

/-! # Two group-theoretic comparisons

This file settles two questions about group-theoretic structure on the frame's data.

**Question 1: `L(3)(𝔽₂) ≟ 𝔤₂(𝔽₂)`.** The motivation is the dimension coincidence: the free class-3
nilpotent Lie algebra on 3 generators has graded dimensions `3 + 3 + 8 = 14 = dim 𝔤₂` (Witt's
formula — characteristic-independent for free Lie algebras). The isomorphism is **structurally
false**, and no table computation is needed. `L(3)` is nilpotent by construction; `𝔤₂(𝔽₂)` is not —
the G₂ Cartan matrix `[[2,−1],[−3,2]]` has odd off-diagonal entries, so pairings `⟨β,α∨⟩ ∈ {−1,−3}`
survive mod 2 and give `⁅h, x⁆ = x` on root vectors (`(ad h)^k x = x ≠ 0` forever).
`FTQCLib/Explore/GTwo.lean` builds `𝔤₂(𝔽₂)` from its root data alone and machine-checks the
eigenvector — `lie_Hg_Xg` + `Xg_ne_zero` + this file's dichotomy give `g2_not_nilpotent` and
`not_nilpotent_of_surjective_g2`; the exact-dimension/closure refinement is in `GTwoCert.lean`
(kernel-heavy, verified by compiled evaluation, built on demand). (G₂'s special prime is 3, not 2 —
the char-2 special isogenies are B/C/F₄.) The decisive statement is the **dichotomy lemma**
(`eq_zero_of_lie_eq_self`): *in any nilpotent Lie algebra, `⁅h, x⁆ = x` forces `x = 0`* — so no
nilpotent Lie algebra whatsoever is isomorphic to one carrying a nonzero ad-eigenvector of
eigenvalue 1. This settles the question for **every** nilpotent candidate at once: `L(3)(𝔽₂)`, every
quotient of it, and — via `LieClosure.lean` (the frame's difference data generates only abelian
brackets, abelian ⊂ nilpotent) — anything Lie-shaped built from the frame's own difference calculus.
What remains of Nekovář's char-0 remark ("h(3) acts through G₂") is therefore not an isomorphism
question but an action question — whether `𝔤₂(𝔽₂)` acts on the frame's cubic data — which is not a
finite computation and is not addressed here.

**Question 2: "Aut(cubic) ∩ Sp".** This is **not posable as stated** — the polarized cubic lives on
`𝔽₂³` (odd-dimensional carrier), the symplectic group on `𝔽₂^{2n}` (even); there is no common
carrier for the literal intersection. The nearest posable object is the stabilizer of the sign
cocycle inside the symplectic group, `{g ∈ Sp : β(g·, g·) = β(·,·)}` — and
`betaStab_iff_frameDistortion_zero` identifies it as **the vanishing locus of `frameDistortion`**,
an object already studied in the frame (the distortion is the metaplectic sign-defect; its
non-vanishing and cubic ceiling on transvections are the `CubicCeiling` / `MetaplecticAction`
results; `betaFrame_not_biadditive_on_isotropic` shows how far from invariant β is). So the question
reduces to existing objects: the candidate "reconciling subgroup" is the distortion-free subgroup,
already known to be small and already central to the frame's sign theory — no new computation adds
information beyond what the distortion results carry.

**Summary.** Question 1: no nilpotent object — in particular nothing the frame's difference data can
generate — is `𝔤₂(𝔽₂)`; the exceptional analogy survives only as an unposed action question.
Question 2: not posable as stated; its content is the existing distortion theory. Together with the
`Aut(cubic) = GL` collapse (`CubicAut.lean`) and the no-central-covers constraint (n ≥ 3), no
constructive group-theoretic route remains open on current knowledge. An exploratory file, not part
of the `FTQCLib` target.
-/

namespace FTQCLib.Explore.GroupDoors

open FTQCLib.Pauli FTQCLib.Frame

/-! ## Question 1: the dichotomy lemma -/

/-- **In a nilpotent Lie algebra, `⁅h, x⁆ = x` forces `x = 0`** — nilpotent Lie algebras carry no
nonzero ad-eigenvector of eigenvalue 1. Since the char-2 Chevalley `𝔤₂(𝔽₂)` carries such
eigenvectors (odd Cartan pairings survive mod 2), **no nilpotent Lie algebra is isomorphic to it** —
in particular not the free class-3 object `L(3)(𝔽₂)` of the dimension coincidence, nor anything
generated by the frame's (abelian, see `LieClosure.lean`) difference data. -/
theorem eq_zero_of_lie_eq_self {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
    [LieRing.IsNilpotent L] (h x : L) (hx : ⁅h, x⁆ = x) : x = 0 := by
  obtain ⟨k, hk⟩ := LieAlgebra.nilpotent_ad_of_nilpotent_algebra (R := R) (L := L)
  have hpow : ∀ m : ℕ, (LieAlgebra.ad R L h ^ m) x = x := by
    intro m
    induction m with
    | zero => simp
    | succ m ih =>
        rw [pow_succ', Module.End.mul_apply, ih, LieAlgebra.ad_apply, hx]
  have h0 := hpow k
  rw [hk h] at h0
  simpa using h0.symm

/-! ## Question 2: the identification -/

/-- **The symplectic stabilizer of the sign cocycle is the vanishing locus of the distortion:** `g`
preserves `betaFrame` iff `frameDistortion g ≡ 0`. The candidate "reconciling subgroup" is therefore
an already-studied frame object — the distortion-free locus — whose smallness is exactly what the
distortion theory (`frameDistortion_rankOne`, the cubic ceiling,
`betaFrame_not_biadditive_on_isotropic`) measures. -/
theorem betaStab_iff_frameDistortion_zero {n : ℕ} (g : Pauli n ≃ₗ[ZMod 2] Pauli n) :
    (∀ a b, betaFrame (g a) (g b) = betaFrame a b) ↔ ∀ a b, frameDistortion g a b = 0 := by
  constructor
  · intro h a b
    rw [frameDistortion, h a b, sub_self]
  · intro h a b
    have := h a b
    rwa [frameDistortion, sub_eq_zero] at this

end FTQCLib.Explore.GroupDoors
