/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Explore.GTwo

set_option linter.style.longLine false

/-! # `𝔤₂(𝔽₂)` — the closure certification (kernel-heavy, build on demand)

The companion to `FTQCLib/Explore/GTwo.lean`. That file's `g2` is the Lie subalgebra GENERATED by the fourteen
adjoint matrices of the root-derived Chevalley table — closed by construction, so the non-nilpotency
discharge there needs only cheap `decide`s. THIS file certifies the two facts that pin `g2` down exactly:

* `ad_closure` — the closure equations `⁅adMat i, adMat j⁆ = ad ⁅eᵢ, eⱼ⁆` over all 14² pairs. These ARE
  the Jacobi identity of the bracket table (`ad` is a homomorphism iff Jacobi holds), so a wrong table
  cannot pass this check;
* `g2_eq_span` — hence the generators are already bracket-closed and `g2` IS the 14-dimensional span
  (with `toMat_injective` from the main file: dimension exactly 14, so the table algebra is center-free —
  the Chevalley algebra of type G₂ over `𝔽₂` itself, not a quotient).

**Build note.** The `ad_closure` `decide` is a long, resource-heavy kernel reduction (more than
12 minutes at 12M heartbeats without completing, and it can exhaust the memory of a small machine).
It is therefore isolated here: this module is imported by nothing and is built only on demand
(`lake build FTQCLib.Explore.GTwoCert`; the heartbeat budget below is generous and may need
raising). **Verification status:** the closure equations hold by compiled evaluation
(`#eval decide (∀ i j, adMat i * adMat j + adMat j * adMat i = toMat (t i j)) = true`); the
kernel check is the build of this module. `GTwo.lean`'s discharge is unconditional as stated
there, and the `g2 = span`/dimension-exactly-14 refinement rests on this module's kernel check. -/

namespace FTQCLib.Explore.GTwo

set_option maxHeartbeats 400000000 in
/-- **The closure equations — which ARE the Jacobi identity of the table:**
`⁅adMat i, adMat j⁆ = ad ⁅eᵢ, eⱼ⁆`. `ad` is a homomorphism iff Jacobi holds, so a wrong table cannot pass
this check. -/
theorem ad_closure : ∀ i j : Fin 14, ⁅adMat i, adMat j⁆ = toMat (tLit i j) := by decide

/-- The 14-dimensional span, as a Lie subalgebra — well-defined exactly because of `ad_closure`. -/
def g2Span : LieSubalgebra (ZMod 2) (Matrix (Fin 14) (Fin 14) (ZMod 2)) where
  toSubmodule := LinearMap.range toMat
  lie_mem' := by
    intro a b ha hb
    obtain ⟨v, rfl⟩ := LinearMap.mem_range.mp ha
    obtain ⟨w, rfl⟩ := LinearMap.mem_range.mp hb
    refine LinearMap.mem_range.mpr ⟨∑ i, ∑ j, (v i * w j) • tLit i j, ?_⟩
    have h1 : toMat (∑ i, ∑ j, (v i * w j) • tLit i j)
        = ∑ i, ∑ j, (v i * w j) • toMat (tLit i j) := by
      rw [map_sum]
      exact Finset.sum_congr rfl fun i _ => by
        rw [map_sum]
        exact Finset.sum_congr rfl fun j _ => map_smul toMat _ _
    have h2 : (⁅toMat v, toMat w⁆ : Matrix (Fin 14) (Fin 14) (ZMod 2))
        = ∑ i, ∑ j, (v i * w j) • ⁅adMat i, adMat j⁆ := by
      rw [toMat_apply, toMat_apply, sum_lie]
      exact Finset.sum_congr rfl fun i _ => by
        rw [lie_sum]
        exact Finset.sum_congr rfl fun j _ => by
          rw [smul_lie, lie_smul, smul_smul]
    rw [h1, h2]
    exact Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => by
      rw [ad_closure]

/-- **`g2` is exactly the 14-dimensional span:** the generated subalgebra collapses to the linear span
because the generators are already bracket-closed. With `toMat_injective`, `g2` has dimension exactly 14
and the table algebra is center-free. -/
theorem g2_eq_span : g2 = g2Span := by
  refine le_antisymm ?_ ?_
  · rw [g2, LieSubalgebra.lieSpan_le]
    rintro a ⟨i, rfl⟩
    exact LinearMap.mem_range.mpr ⟨eVec i, toMat_eVec i⟩
  · intro a ha
    obtain ⟨v, rfl⟩ := LinearMap.mem_range.mp ha
    rw [toMat_apply]
    exact Submodule.sum_mem _ fun i _ =>
      Submodule.smul_mem _ _ (LieSubalgebra.subset_lieSpan ⟨i, rfl⟩)

end FTQCLib.Explore.GTwo
