/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import ECCLib.GateCarrier

set_option linter.unusedSectionVars false

/-!
# Certified irreducibility from a decided inverse table

The engine that certifies irreducibility at m = 8. For a reduction word `r`, the quotient
`AdjoinRoot ν` is a commutative ring with **no irreducibility needed** (`GateField`); if a table
`inv` of coordinate vectors satisfies the *decidable* statement `∀ v ≠ 0, mulVecC r v (inv v) = 1`,
then every nonzero element of the quotient is a unit — through the evaluation `emb` and its
multiplicativity (`emb_mulVecC`) — so the quotient `IsField`, the ideal `span {ν}` is maximal
(`Ideal.Quotient.maximal_of_isField`), hence prime, hence **`ν` is irreducible**. The table needs no
trust: a wrong table simply fails the `decide`.

Instantiations:

* **GF(16), primitive**: `ν₄′ = X⁴ + X + 1` — 15 kernel products certify irreducibility, and the
  same `emb` machinery certifies `orderOf (root ν₄′) = 15`: **the root is a primitive element**,
  unlike `Φ₅`'s (order 5). This is the carrier RS evaluation families want.
* **GF(256), the AES field**: `ν₈ = X⁸+X⁴+X³+X+1`,
  255 kernel products (measured at 4,103 heartbeats each), giving `Irreducible ν₈` — so
  **`GF256 := AdjoinRoot ν₈` is a field with the AES polynomial pinned by name**, its certified
  multiplier netlist already built (`mulNet_adjBasis`), and its classification bridge
  `GF256 ≃ₐ[ZMod 2] GaloisField 2 8` free from `adjEquivGaloisField`.

The inverse tables were generated by the materialised List model (generation runs in the
interpreter, where the List model is fast) and are certified per-entry by the kernel here.
-/

namespace ECCLib

open Module Polynomial

/-! ## The evaluation is a coordinate system -/

section Coords

variable (m : ℕ) (r : Fin (m + 1) → ZMod 2)

/-- Every element of the quotient is the evaluation of its coordinate word. -/
theorem emb_root_coords (x : AdjoinRoot (nu m r)) :
    emb (AdjoinRoot.root (nu m r)) (fun i => (adjBasis m r).repr x i) = x := by
  unfold emb
  simp only [← adjBasis_apply m r]
  exact Basis.sum_repr _ x

/-- The coordinates of an evaluation are the word itself. -/
theorem coords_emb (v : Fin (m + 1) → ZMod 2) :
    ⇑((adjBasis m r).repr (emb (AdjoinRoot.root (nu m r)) v)) = v := by
  unfold emb
  simp only [← adjBasis_apply m r]
  exact Basis.repr_sum_self _ _

theorem emb_injective :
    Function.Injective (emb (AdjoinRoot.root (nu m r)) : (Fin (m + 1) → ZMod 2) → _) := by
  intro v w h
  rw [← coords_emb m r v, ← coords_emb m r w, h]

/-- A model-level power inequality transports to the root. -/
theorem root_pow_ne_one {n : ℕ} (h : powVec r n ≠ powVec r 0) :
    (AdjoinRoot.root (nu m r)) ^ n ≠ 1 := by
  intro h1
  apply h
  apply emb_injective m r
  rw [emb_powVec r _ (root_pow_top m r) n, emb_powVec r _ (root_pow_top m r) 0, pow_zero, h1]

end Coords

/-! ## The engine -/

/-- **Certified irreducibility from a decided inverse table.** If a table `inv` satisfies the
decidable per-entry statement `∀ v ≠ 0, mulVecC r v (inv v) = 1`, then `ν` is irreducible. The
table needs no trust — a wrong table fails the `decide` that discharges the hypothesis. -/
theorem irreducible_of_inv {m : ℕ} (r : Fin (m + 1) → ZMod 2)
    (inv : (Fin (m + 1) → ZMod 2) → (Fin (m + 1) → ZMod 2))
    (hinv : ∀ v, v ≠ 0 → mulVecC r v (inv v) = powVec r 0) :
    Irreducible (nu m r) := by
  have hα := root_pow_top m r
  have hfield : IsField (AdjoinRoot (nu m r)) := by
    haveI : Nontrivial (AdjoinRoot (nu m r)) := by
      refine Fintype.one_lt_card_iff_nontrivial.mp ?_
      rw [card_adjoinRoot_nu]
      exact Nat.one_lt_two_pow_iff.mpr (Nat.succ_ne_zero m)
    refine ⟨exists_pair_ne _, mul_comm, ?_⟩
    intro x hx
    set v : Fin (m + 1) → ZMod 2 := fun i => (adjBasis m r).repr x i with hvdef
    have hxv : emb (AdjoinRoot.root (nu m r)) v = x := emb_root_coords m r x
    have hv0 : v ≠ 0 := by
      intro h0
      apply hx
      rw [← hxv, h0]
      simp [emb]
    refine ⟨emb (AdjoinRoot.root (nu m r)) (inv v), ?_⟩
    calc x * emb (AdjoinRoot.root (nu m r)) (inv v)
        = emb (AdjoinRoot.root (nu m r)) v * emb (AdjoinRoot.root (nu m r)) (inv v) := by
          rw [hxv]
      _ = emb (AdjoinRoot.root (nu m r)) (mulVecC r v (inv v)) :=
          (emb_mulVecC r _ hα v (inv v)).symm
      _ = emb (AdjoinRoot.root (nu m r)) (powVec r 0) := by rw [hinv v hv0]
      _ = 1 := by rw [emb_powVec r _ hα 0, pow_zero]
  have hmax : (Ideal.span {nu m r} : Ideal (Polynomial (ZMod 2))).IsMaximal :=
    Ideal.Quotient.maximal_of_isField _ hfield
  have hprime : Prime (nu m r) :=
    (Ideal.span_singleton_prime (nu_monic m r).ne_zero).mp hmax.isPrime
  exact hprime.irreducible

/-! ## The table interface -/

/-- Little-endian index of a coordinate word. -/
def idxOf {m : ℕ} (v : Fin (m + 1) → ZMod 2) : ℕ := ∑ i, (v i).val * 2 ^ (i : ℕ)

/-- Look a coordinate word up in a literal table. -/
def tblInv (L : List (List ℕ)) {m : ℕ} (v : Fin (m + 1) → ZMod 2) : Fin (m + 1) → ZMod 2 :=
  fun k => (((L.getD (idxOf v) []).getD (k : ℕ) 0 : ℕ) : ZMod 2)

/-! ## GF(16), primitive: `ν₄′ = X⁴ + X + 1` -/

/-- The primitive GF(16) reduction word: `α⁴ = α + 1`. -/
def r4p : Fin 4 → ZMod 2 := fun k => if k.val ≤ 1 then 1 else 0

/-- The 16-row inverse table for `ν₄′`, generated by the List model. -/
def inv4L : List (List ℕ) :=
  [[0,0,0,0], [1,0,0,0], [1,0,0,1], [0,1,1,1], [1,0,1,1], [1,1,0,1], [1,1,1,0], [0,1,1,0],
   [1,1,1,1], [0,1,0,0], [0,0,1,1], [1,0,1,0], [0,1,0,1], [0,0,1,0], [1,1,0,0], [0,0,0,1]]

/-- The named GF(16) inverse-table certificate: decided once, consumed by both
`nu4p_irreducible` and the decoder's `gf16Model`. -/
theorem inv4_cert : ∀ v : Fin 4 → ZMod 2, v ≠ 0 →
    mulVecC r4p v (tblInv inv4L v) = powVec r4p 0 := by
  decide

/-- Row zero of the table is zero — the totality of the inverse (`0⁻¹ = 0`). -/
theorem tblInv_inv4L_zero : tblInv inv4L (0 : Fin 4 → ZMod 2) = 0 := by decide

/-- **`X⁴ + X + 1` is irreducible over `𝔽₂`** — by 15 kernel products. -/
theorem nu4p_irreducible : Irreducible (nu 3 r4p) :=
  irreducible_of_inv r4p (tblInv inv4L) inv4_cert

instance : Fact (Irreducible (nu 3 r4p)) := ⟨nu4p_irreducible⟩

/-- **GF(16) with a primitive named polynomial** — the carrier RS evaluation families want. -/
noncomputable abbrev GF16p := AdjoinRoot (nu 3 r4p)

noncomputable def gf16pEquivGaloisField : GF16p ≃ₐ[ZMod 2] GaloisField 2 4 :=
  adjEquivGaloisField 3 r4p

/-- **The root of `ν₄′` is a primitive element**: its multiplicative order is `15 = 16 − 1`.
Model facts (`α¹⁵ = 1`, `α⁵ ≠ 1`, `α³ ≠ 1`) transport through the evaluation. -/
theorem orderOf_root_GF16p : orderOf (AdjoinRoot.root (nu 3 r4p)) = 15 := by
  have hα := root_pow_top 3 r4p
  refine orderOf_eq_of_pow_and_pow_div_prime (by norm_num) ?_ ?_
  · have h := emb_powVec r4p (AdjoinRoot.root (nu 3 r4p)) hα 15
    rw [show powVec r4p 15 = powVec r4p 0 from by decide,
      emb_powVec r4p _ hα 0, pow_zero] at h
    exact h.symm
  · intro p hp hdvd
    have h35 : p = 3 ∨ p = 5 := by
      have h2 := hp.two_le
      have h15 : p ≤ 15 := Nat.le_of_dvd (by norm_num) hdvd
      interval_cases p <;> revert hp hdvd <;> decide
    rcases h35 with rfl | rfl
    · exact root_pow_ne_one 3 r4p (by decide)
    · exact root_pow_ne_one 3 r4p (by decide)

/-! ## GF(256), the AES field: `ν₈ = X⁸ + X⁴ + X³ + X + 1` -/

/-- The 256-row inverse table for the AES word, generated by the List model. -/
def inv8L : List (List ℕ) :=
  [[0,0,0,0,0,0,0,0], [1,0,0,0,0,0,0,0], [1,0,1,1,0,0,0,1], [0,1,1,0,1,1,1,1],
   [1,1,0,1,0,0,1,1], [0,1,0,0,1,0,1,0], [1,1,0,1,1,1,1,0], [1,0,0,0,1,0,1,1],
   [0,0,0,1,0,1,1,1], [1,1,1,1,0,0,1,0], [1,0,0,1,0,1,0,0], [0,0,0,0,0,0,1,1],
   [0,0,0,0,1,1,0,1], [1,0,0,0,0,1,1,1], [1,0,1,0,0,1,1,1], [1,1,1,0,0,0,1,1],
   [0,0,1,0,1,1,1,0], [0,0,1,0,1,1,0,1], [0,1,0,1,0,1,0,1], [1,1,0,1,0,0,1,0],
   [1,0,0,1,1,0,0,1], [1,1,0,1,0,1,0,0], [0,0,0,0,0,1,1,0], [1,1,1,1,1,0,1,0],
   [0,0,0,1,1,0,1,0], [1,1,1,1,1,1,0,0], [1,0,1,1,1,1,1,1], [0,0,1,1,0,0,1,1],
   [1,1,1,1,1,1,1,1], [0,0,0,0,0,0,1,0], [0,1,1,1,0,1,1,1], [0,1,0,0,1,1,0,1],
   [0,1,0,1,1,1,0,0], [0,1,1,1,0,1,1,0], [0,1,0,1,1,0,1,0], [1,0,0,0,1,1,1,1],
   [1,0,1,0,1,0,1,0], [1,0,1,1,0,0,1,0], [0,0,0,1,0,1,0,1], [1,0,0,1,0,0,1,1],
   [1,0,0,0,0,0,1,1], [0,1,0,1,0,0,0,0], [0,0,0,1,1,0,0,1], [1,0,1,0,1,0,0,0],
   [0,0,0,0,1,1,0,0], [0,0,1,0,0,0,1,0], [0,1,0,0,0,1,0,1], [0,1,0,0,0,0,1,1],
   [0,0,1,1,0,1,0,0], [1,0,1,0,0,0,1,0], [0,1,0,0,1,0,0,1], [0,0,1,1,0,1,1,0],
   [1,1,0,0,1,1,1,1], [1,0,0,1,1,1,0,0], [0,1,1,0,0,1,1,0], [0,1,0,0,0,0,1,0],
   [0,1,0,0,1,1,1,1], [1,0,1,0,1,1,0,0], [0,0,0,0,0,1,0,0], [1,1,1,1,0,1,1,0],
   [1,1,1,0,1,1,1,0], [1,1,0,1,1,1,0,1], [1,0,0,1,1,0,1,0], [1,0,0,1,1,0,0,0],
   [1,0,1,1,1,0,0,0], [0,1,1,1,1,1,1,1], [1,1,1,0,1,1,0,0], [1,1,1,0,0,1,1,0],
   [1,0,1,1,0,1,0,0], [1,0,0,0,1,1,0,0], [1,0,1,0,1,1,1,1], [1,0,0,1,0,1,1,0],
   [1,1,1,0,0,1,0,1], [0,0,1,0,0,1,1,0], [1,1,0,1,0,1,0,1], [1,1,0,0,1,0,0,0],
   [0,0,1,0,1,0,1,0], [1,0,1,0,0,1,0,0], [1,0,0,1,0,1,1,1], [1,0,0,1,0,0,0,0],
   [1,0,1,1,0,1,1,1], [0,0,1,1,1,0,1,0], [1,0,1,0,0,0,0,0], [0,1,0,1,0,0,1,1],
   [0,0,1,1,0,0,1,0], [0,0,1,0,0,1,0,0], [1,1,1,0,0,0,0,1], [1,1,1,1,1,1,0,1],
   [0,0,0,1,1,0,0,0], [0,1,1,1,1,1,0,0], [0,1,0,0,0,1,0,0], [0,0,0,0,1,1,1,1],
   [1,0,0,0,1,0,1,0], [0,0,1,1,0,1,1,1], [1,0,0,0,0,1,1,0], [1,1,1,0,1,0,0,0],
   [0,1,1,0,1,0,0,0], [0,1,1,1,1,0,1,0], [1,1,1,1,0,1,0,1], [1,1,0,0,1,0,1,1],
   [1,0,0,1,0,0,1,0], [0,1,1,0,0,1,0,1], [0,1,1,0,1,1,0,0], [1,1,0,0,0,0,1,0],
   [0,0,1,0,1,1,1,1], [1,1,1,0,0,0,1,0], [1,0,0,0,1,0,0,1], [1,1,1,1,1,0,1,1],
   [1,1,0,0,1,1,0,0], [1,1,0,0,1,0,0,1], [1,0,0,0,0,1,0,0], [1,1,0,1,1,1,0,0],
   [1,0,0,1,1,1,1,0], [1,1,1,0,1,1,0,1], [1,1,1,0,1,0,0,1], [1,0,1,0,0,0,0,1],
   [0,0,0,0,1,0,0,0], [1,0,1,0,1,1,0,1], [0,1,0,1,1,1,0,1], [0,0,1,1,1,1,0,0],
   [0,1,1,0,1,1,0,1], [0,0,0,0,1,1,1,0], [0,0,0,0,1,0,1,1], [0,1,1,0,0,0,0,0],
   [1,0,0,0,0,1,0,1], [0,1,0,1,1,1,1,1], [1,0,0,0,0,0,0,1], [0,1,0,0,0,0,0,1],
   [1,1,0,0,0,0,0,1], [0,1,1,1,1,1,1,0], [1,1,1,1,1,1,1,0], [0,0,0,0,0,0,0,1],
   [0,1,1,0,1,0,0,1], [1,1,0,0,1,1,1,0], [0,1,1,1,1,1,0,1], [0,1,1,0,1,0,1,0],
   [1,1,0,1,1,0,0,1], [0,1,1,1,1,0,0,1], [1,0,1,0,1,0,0,1], [1,0,0,1,1,0,1,1],
   [1,1,1,0,1,1,1,1], [0,1,0,0,0,0,0,0], [1,0,0,1,1,1,0,1], [0,0,1,0,0,1,0,1],
   [0,1,1,1,1,0,1,1], [0,1,0,1,0,1,1,0], [0,1,0,0,1,1,0,0], [1,0,1,1,0,1,1,0],
   [0,0,0,1,1,0,1,1], [0,1,0,1,0,0,0,1], [0,0,1,0,0,0,0,1], [0,1,0,0,1,1,1,0],
   [0,1,0,1,0,1,0,0], [0,0,1,0,1,0,0,0], [1,1,1,1,1,0,0,1], [0,0,0,1,0,0,0,1],
   [1,0,0,1,1,1,1,1], [0,0,1,1,1,0,1,1], [1,0,0,1,0,0,0,1], [0,1,0,1,1,0,0,1],
   [1,1,0,1,1,1,1,1], [0,0,1,1,1,1,1,0], [0,1,1,1,0,1,0,0], [1,1,0,0,0,0,1,1],
   [1,1,1,1,0,0,0,1], [0,0,0,1,1,1,0,1], [1,0,1,0,0,1,1,0], [0,0,0,1,0,0,1,0],
   [0,1,1,0,0,1,0,0], [0,0,0,1,0,0,1,1], [0,1,0,0,1,0,0,0], [0,1,0,1,0,0,1,0],
   [0,1,1,1,0,0,1,1], [1,1,1,0,0,1,1,1], [0,1,0,0,1,0,1,1], [0,1,0,0,0,1,1,0],
   [0,0,1,1,0,0,0,0], [0,0,0,0,0,1,1,1], [1,1,1,1,1,0,0,0], [1,1,1,1,0,1,1,1],
   [1,0,0,0,1,0,0,0], [1,0,1,0,1,1,1,0], [0,0,0,1,1,1,1,0], [1,0,0,0,1,1,1,0],
   [1,0,1,0,0,1,0,1], [0,1,1,1,0,0,0,1], [0,1,1,0,1,1,1,0], [1,0,1,1,1,1,0,0],
   [1,0,1,1,1,1,0,1], [0,0,1,1,1,1,0,1], [0,1,1,0,0,0,0,1], [1,1,1,0,1,0,1,0],
   [1,1,0,1,0,0,0,0], [0,0,0,1,0,1,0,0], [1,1,1,1,0,1,0,0], [1,1,0,0,0,1,0,1],
   [0,1,0,1,1,0,1,1], [0,0,1,0,1,0,1,1], [0,0,1,0,0,1,1,1], [1,1,1,1,0,0,0,0],
   [1,0,0,1,0,1,0,1], [1,1,1,0,0,1,0,0], [1,1,0,0,1,0,1,0], [0,0,1,0,0,0,0,0],
   [1,1,0,1,1,0,0,0], [0,0,1,1,1,1,1,1], [0,0,1,1,0,1,0,1], [0,1,1,0,0,1,1,1],
   [0,1,0,1,1,1,1,0], [1,1,1,0,0,0,0,0], [0,1,1,1,0,1,0,1], [1,1,0,0,0,1,1,0],
   [1,0,1,0,0,0,1,1], [1,1,0,1,1,0,1,1], [0,1,0,0,0,1,1,1], [0,1,0,1,0,1,1,1],
   [0,0,1,0,1,0,0,1], [1,1,0,1,0,0,0,1], [0,0,1,0,0,0,1,1], [1,0,1,0,1,0,1,1],
   [1,0,1,1,1,0,0,1], [0,0,0,1,1,1,1,1], [0,0,0,0,1,0,0,1], [1,1,0,1,0,1,1,0],
   [1,0,0,0,1,1,0,1], [1,0,1,1,0,0,0,0], [0,1,1,0,1,0,1,1], [1,1,0,1,0,1,1,1],
   [0,1,1,0,0,0,1,1], [0,1,1,1,0,0,0,0], [1,1,1,1,0,0,1,1], [1,0,1,1,0,1,0,1],
   [0,0,0,1,0,0,0,0], [0,1,1,1,0,0,1,0], [1,1,1,0,1,0,1,1], [1,1,0,0,0,1,1,1],
   [1,0,1,1,1,0,1,0], [0,0,0,0,1,0,1,0], [0,1,1,1,1,0,0,0], [1,1,0,0,1,1,0,1],
   [1,1,0,1,1,0,1,0], [1,1,0,0,0,1,0,0], [0,0,0,1,1,1,0,0], [0,0,1,0,1,1,0,0],
   [0,0,0,1,0,1,1,0], [0,1,1,0,0,0,1,0], [1,1,0,0,0,0,0,0], [0,0,1,1,0,0,0,1],
   [1,0,1,1,1,0,1,1], [0,0,1,1,1,0,0,1], [1,0,1,1,1,1,1,0], [0,0,0,0,0,1,0,1],
   [1,0,1,1,0,0,1,1], [0,1,0,1,1,0,0,0], [1,0,0,0,0,0,1,0], [0,0,1,1,1,0,0,0]]

set_option maxHeartbeats 12000000 in
-- 255 kernel products at ~4,100 heartbeats each (measured) plus table-lookup
-- overhead: ~1.5M heartbeats expected, capped with headroom
set_option maxRecDepth 8192 in
-- the 256-entry list walks nest deeper than the default recursion limit
/-- The named GF(256) inverse-table certificate: the 255-product decide runs ONCE here,
consumed by both `nu8_irreducible` and the decoder's `gf256Model`. -/
theorem inv8_cert : ∀ v : Fin 8 → ZMod 2, v ≠ 0 →
    mulVecC r8 v (tblInv inv8L v) = powVec r8 0 := by
  decide

set_option maxRecDepth 8192 in
/-- Row zero of the AES table is zero. -/
theorem tblInv_inv8L_zero : tblInv inv8L (0 : Fin 8 → ZMod 2) = 0 := by decide

/-- **The AES polynomial `X⁸ + X⁴ + X³ + X + 1` is irreducible over `𝔽₂`** — by 255 kernel
products against the generated inverse table. Hence GF(256) exists with its reduction
polynomial pinned by name. -/
theorem nu8_irreducible : Irreducible (nu 7 r8) :=
  irreducible_of_inv r8 (tblInv inv8L) inv8_cert

instance : Fact (Irreducible (nu 7 r8)) := ⟨nu8_irreducible⟩

/-- **GF(256), the AES field** — a genuine field with the named reduction polynomial, whose
certified multiplier netlist (`mulNet_adjBasis 7 r8`, 727 gates) is already built. -/
noncomputable abbrev GF256 := AdjoinRoot (nu 7 r8)

noncomputable example : Field GF256 := inferInstance

theorem card_GF256 : Fintype.card GF256 = 256 := card_adjoinRoot_nu 7 r8

/-- The classification bridge, free from `adjEquivGaloisField`: the named AES field is the Galois
field. -/
noncomputable def gf256EquivGaloisField : GF256 ≃ₐ[ZMod 2] GaloisField 2 8 :=
  adjEquivGaloisField 7 r8

end ECCLib
