/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import ECCLib.WeilGenerationComplete

set_option linter.unusedSectionVars false
set_option linter.unusedFintypeInType false
set_option linter.unusedDecidableInType false

/-!
# The monomial group inside the symplectic group

The monomial group `M = (F^×)^ι ⋊ S_ι` — coordinate permutations and diagonal-unit scalings — is
the frame-fixing subgroup of `Sp`: the isometry group of the Hamming weight, sitting inside the
Levi of the Siegel parabolic. This file places it in the repo's symplectic world:

* `Heis.permMap σ` — `(p, m, c) ↦ (p∘σ⁻¹, m∘σ⁻¹, c)`, and
  `Heis.dilMap d` — `(p, m, c) ↦ (d·p, d⁻¹·m, c)`: the two generator families, as pointwise `Heis`
  maps in the `mob` idiom;
* both are symplectic (`isSymplectic_permMap`, `isSymplectic_dilMap`) — the dilation needs
  `d i ≠ 0`, the permutation needs nothing;
* the group laws (`permMap_comp`, `dilMap_comp`, `permMap_comp_dilMap` — the semidirect relation);
* membership in `⟨shears, w⟩` (`inWeilGroup_permMap`, `inWeilGroup_dilMap`) — free from
  `inWeilGroup_of_isSymplectic`, so **every monomial map already has a Weil operator**;
  `ECCLib/MonomialWeil.lean` computes what those operators are;
* the rank-one anchor: at `|ι| = 1` the dilation is `mob a 0 0 a⁻¹`.

Design note: no general Levi embedding `A ↦ (Ap, (Aᵀ)⁻¹m)` is defined here; the monomial group
*is* generated by the two families above.
-/

namespace ECCLib.Heisenberg

variable {F : Type*} [Field F] {ι : Type*} [Fintype ι]

namespace Heis

/-! ## The two generator families -/

/-- The **coordinate permutation** `σ · (p, m, c) = (p∘σ⁻¹, m∘σ⁻¹, c)` — the left action of `S_ι`
on both position and momentum. -/
def permMap (σ : Equiv.Perm ι) (x : Heis F ι) : Heis F ι :=
  ⟨fun i => x.pos (σ⁻¹ i), fun i => x.mom (σ⁻¹ i), x.cen⟩

@[simp] lemma permMap_pos (σ : Equiv.Perm ι) (x : Heis F ι) :
    (permMap σ x).pos = fun i => x.pos (σ⁻¹ i) := rfl
@[simp] lemma permMap_mom (σ : Equiv.Perm ι) (x : Heis F ι) :
    (permMap σ x).mom = fun i => x.mom (σ⁻¹ i) := rfl
@[simp] lemma permMap_cen (σ : Equiv.Perm ι) (x : Heis F ι) : (permMap σ x).cen = x.cen := rfl

/-- The **diagonal scaling** `d · (p, m, c) = (d·p, d⁻¹·m, c)` — positions scaled by `d`, momenta by
`d⁻¹`, the shape forced by the symplectic form. -/
def dilMap (d : ι → F) (x : Heis F ι) : Heis F ι :=
  ⟨fun i => d i * x.pos i, fun i => (d i)⁻¹ * x.mom i, x.cen⟩

@[simp] lemma dilMap_pos (d : ι → F) (x : Heis F ι) :
    (dilMap d x).pos = fun i => d i * x.pos i := rfl
@[simp] lemma dilMap_mom (d : ι → F) (x : Heis F ι) :
    (dilMap d x).mom = fun i => (d i)⁻¹ * x.mom i := rfl
@[simp] lemma dilMap_cen (d : ι → F) (x : Heis F ι) : (dilMap d x).cen = x.cen := rfl

/-! ## Both are symplectic -/

lemma pairing_perm (σ : Equiv.Perm ι) (b y : ι → F) :
    pairing (fun i => b (σ⁻¹ i)) (fun i => y (σ⁻¹ i)) = pairing b y := by
  unfold pairing
  exact Equiv.sum_comp σ⁻¹ (fun i => b i * y i)

/-- Permutations are symplectic. -/
theorem isSymplectic_permMap (σ : Equiv.Perm ι) :
    IsSymplectic (permMap (F := F) σ) where
  map_pos x y := by
    funext i
    simp only [permMap_pos, mul_pos, Pi.add_apply]
  map_mom x y := by
    funext i
    simp only [permMap_mom, mul_mom, Pi.add_apply]
  map_cen x := rfl
  map_symp x y := by
    unfold symp
    simp only [permMap_pos, permMap_mom]
    rw [pairing_perm, pairing_perm]

/-- Diagonal scalings by nonvanishing `d` are symplectic: the `d` on positions cancels the `d⁻¹` on
momenta inside the form. -/
theorem isSymplectic_dilMap {d : ι → F} (hd : ∀ i, d i ≠ 0) :
    IsSymplectic (dilMap (F := F) d) where
  map_pos x y := by
    funext i
    simp only [dilMap_pos, mul_pos, Pi.add_apply]
    ring
  map_mom x y := by
    funext i
    simp only [dilMap_mom, mul_mom, Pi.add_apply]
    ring
  map_cen x := rfl
  map_symp x y := by
    unfold symp pairing
    rw [← Finset.sum_sub_distrib, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun i _ => ?_
    simp only [dilMap_pos, dilMap_mom]
    field_simp
    exact mul_div_cancel_left₀ _ (hd i)

/-! ## The group laws -/

theorem permMap_comp (σ τ : Equiv.Perm ι) :
    permMap (F := F) σ ∘ permMap τ = permMap (σ * τ) := by
  funext x
  refine Heis.ext ?_ ?_ rfl <;> funext i <;>
    simp only [Function.comp_apply, permMap_pos, permMap_mom, mul_inv_rev,
      Equiv.Perm.mul_apply]

theorem dilMap_comp (d e : ι → F) :
    dilMap (F := F) d ∘ dilMap e = dilMap (d * e) := by
  funext x
  refine Heis.ext ?_ ?_ rfl <;> funext i
  · simp only [Function.comp_apply, dilMap_pos, Pi.mul_apply]
    ring
  · simp only [Function.comp_apply, dilMap_mom, Pi.mul_apply, mul_inv]
    ring

/-- The semidirect relation: conjugating a scaling by a permutation permutes the scaling vector. -/
theorem permMap_comp_dilMap (σ : Equiv.Perm ι) (d : ι → F) :
    permMap (F := F) σ ∘ dilMap d = dilMap (fun i => d (σ⁻¹ i)) ∘ permMap σ := by
  funext x
  refine Heis.ext ?_ ?_ rfl <;> funext i <;>
    simp only [Function.comp_apply, permMap_pos, permMap_mom, dilMap_pos, dilMap_mom]

end Heis

/-! ## Membership: every monomial map is a word in the shears and `w` -/

section Membership

variable [Fintype F] [DecidableEq ι]

open ECCLib.WeilComplete

/-- Permutations lie in `⟨shears, w⟩` — hence carry Weil operators. -/
theorem inWeilGroup_permMap (σ : Equiv.Perm ι) :
    InWeilGroup (Heis.permMap (F := F) σ) :=
  inWeilGroup_of_isSymplectic (Heis.isSymplectic_permMap σ)

/-- Diagonal scalings lie in `⟨shears, w⟩` — hence carry Weil operators. -/
theorem inWeilGroup_dilMap {d : ι → F} (hd : ∀ i, d i ≠ 0) :
    InWeilGroup (Heis.dilMap (F := F) d) :=
  inWeilGroup_of_isSymplectic (Heis.isSymplectic_dilMap hd)

end Membership

/-! ## The rank-one anchor -/

/-- At `|ι| = 1` the diagonal scaling is the `mob` torus element `diag(a, a⁻¹)` of the rank-one
classification. -/
theorem dilMap_eq_mob [Unique ι] (d : ι → F) :
    Heis.dilMap (F := F) d = mob (d default) 0 0 (d default)⁻¹ := by
  funext x
  refine Heis.ext ?_ ?_ rfl <;> funext i
  · simp only [Heis.dilMap_pos, mob_pos]
    rw [Unique.eq_default i]
    ring
  · simp only [Heis.dilMap_mom, mob_mom]
    rw [Unique.eq_default i]
    ring

end ECCLib.Heisenberg
