/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Gates.Clifford
import FTQCLib.Gates.TransvectionAbstract

/-!
# The Clifford gates generate the symplectic group

The symplectic group `Sp(2n, 𝔽₂) = Aut(Pauli n, ω)` is generated by the four elementary Clifford
gate families `H_k`, `S_k`, `CNOT_{ij}`, `CZ_{ij}` acting on `Pauli n`
(`closure_bigGateSet_eq_spSubgroup`). The proof is in two halves: **(i)** the symplectic
transvections generate `Sp` — the char-2 Cartan–Dieudonné theorem of
`FTQCLib/Gates/TransvectionAbstract.lean`, specialised to `omegaBilin`
(`transvectionEquiv_closure_eq_spSubgroup`); and **(ii)** every transvection is a word in the gates
(`transvection_mem`), proved by induction on `pauliSupport`, the set of bits where a Pauli is
non-trivial: a `CNOT` clears one bit at a time (`cnot_clears`, `support_reduction`) until the
support has one element, where `H`, `S` and `CZ` cover the three single-bit transvections.

Everything here is a statement about `Pauli n ≃ₗ[ZMod 2] Pauli n` and the form `ω`; no complex
amplitude and no `FTQCLib.Hilbert` appears, so frame-pure consumers can use the generation theorem
without importing the Hilbert layer. The Hilbert modules `FTQCLib/Hilbert/AffineSymplectic.lean` and
`FTQCLib/Hilbert/SymplecticGeneration.lean` import this one for their corollaries (surjectivity of
`cliffordToSp` onto `Sp`).

## Main definitions

* `spSubgroup n` — the symplectic group as a subgroup of `Pauli n ≃ₗ[ZMod 2] Pauli n`.
* `bigGateSet n` — the four gate families as a subset of that group.
* `cliffordGateGens n` — the same four families as elements of the subtype `↥(spSubgroup n)`.
* `SpGeneratedByCliffordGates n` — the generation statement as a named `Prop`.
* `pauliSupport v` — the bits where `v` is not the identity; the induction measure for (ii).

## Main results

* `transvectionEquiv_closure_eq_spSubgroup` — **(i)**: transvections generate `Sp`.
* `transvection_mem` — **(ii)**: every transvection is a word in the gates.
* `closure_bigGateSet_eq_spSubgroup` — (i) + (ii) in the ambient group.
* `spGeneratedByCliffordGates` — the same statement transported to the subtype, discharging
  `SpGeneratedByCliffordGates`.

## Implementation notes

The ambient-group form (`closure_bigGateSet_eq_spSubgroup`) and the subtype form
(`spGeneratedByCliffordGates`) are both kept: the ambient one is what an induction over a word
should use, since the subtype form drags `Subtype.val` through every case, while the subtype form
is what the Hilbert-side surjectivity argument (`FTQCLib/Hilbert/AffineSymplectic.lean`) consumes.
-/

namespace FTQCLib.Gates

open FTQCLib.Pauli

variable {n : ℕ}


/-! ## The symplectic group `Sp(V) = Aut(Pauli n, ω)` -/

/-- The symplectic automorphisms are closed under inverse. -/
theorem isClifford_symm {T : Pauli n ≃ₗ[ZMod 2] Pauli n} (hT : IsClifford T) :
    IsClifford T.symm := by
  intro p q
  have h := hT (T.symm p) (T.symm q)
  simpa only [LinearEquiv.apply_symm_apply] using h.symm

/-- **The symplectic group** `Sp(V)` as a subgroup of `Pauli n ≃ₗ[ZMod 2] Pauli n`. -/
def spSubgroup (n : ℕ) : Subgroup (Pauli n ≃ₗ[ZMod 2] Pauli n) where
  carrier := {T | IsClifford T}
  one_mem' := isClifford_refl
  mul_mem' ha hb := IsClifford.trans hb ha
  inv_mem' ha := isClifford_symm ha

@[simp] theorem mem_spSubgroup {T : Pauli n ≃ₗ[ZMod 2] Pauli n} :
    T ∈ spSubgroup n ↔ IsClifford T := Iff.rfl


/-- The standard generating set of `Sp(V)`: the symplectic images of the elementary Clifford gates
`H_k`, `S_k`, `CNOT_{ij}`, `CZ_{ij}` (each proven `IsClifford`), as elements of `spSubgroup n`. -/
def cliffordGateGens (n : ℕ) : Set (spSubgroup n) :=
  (Set.range fun k : Fin n => (⟨hadamardAt k, hadamardAt_isClifford k⟩ : spSubgroup n))
  ∪ (Set.range fun k : Fin n => (⟨phaseAt k, phaseAt_isClifford k⟩ : spSubgroup n))
  ∪ {g | ∃ (i j : Fin n) (hij : i ≠ j), g = ⟨cnotAt i j hij, cnotAt_isClifford i j hij⟩}
  ∪ {g | ∃ (i j : Fin n) (hij : i ≠ j), g = ⟨czAt i j hij, czAt_isClifford i j hij⟩}

/-- The statement that the elementary Clifford gates generate the full symplectic group
`Sp(2n, 𝔽₂)`, as a named `Prop` — never an `axiom`. It is **proved** below
(`spGeneratedByCliffordGates`), from (i) (transvections generate `Sp`) and (ii) (every transvection
is a gate word); the named form is what the Hilbert-side surjectivity argument takes as a
hypothesis. -/
def SpGeneratedByCliffordGates (n : ℕ) : Prop :=
  Subgroup.closure (cliffordGateGens n) = ⊤


/-- The concrete transvection generating set on `Pauli n` is the abstract one for `omegaBilin`. -/
theorem transvectionGens_omega :
    {h : Pauli n ≃ₗ[ZMod 2] Pauli n | ∃ v, h = transvectionEquiv v}
      = transvectionGens omegaBilin omegaBilin_isAlt := by
  ext h
  simp only [Set.mem_setOf_eq, transvectionGens]
  constructor
  · rintro ⟨v, rfl⟩; exact ⟨v, (transvectionEquivB_omega v).symm⟩
  · rintro ⟨v, rfl⟩; exact ⟨v, transvectionEquivB_omega v⟩

/-- **(i)** The symplectic transvections generate `Sp(2n, 𝔽₂) = spSubgroup n`. -/
theorem transvectionEquiv_closure_eq_spSubgroup :
    Subgroup.closure {h : Pauli n ≃ₗ[ZMod 2] Pauli n | ∃ v, h = transvectionEquiv v}
      = spSubgroup n := by
  apply le_antisymm
  · rw [Subgroup.closure_le]
    rintro h ⟨v, rfl⟩
    exact mem_spSubgroup.mpr (transvectionEquiv_isClifford v)
  · intro T hT
    rw [mem_spSubgroup] at hT
    rw [transvectionGens_omega]
    exact transvections_generate_sp omegaBilin omegaBilin_nondegenerate omegaBilin_isAlt hT

/-- The transvection by `0` is the identity (the base case of (ii), support `0`). -/
theorem transvectionEquiv_zero : transvectionEquiv (0 : Pauli n) = 1 := by
  refine LinearEquiv.ext fun u => ?_
  simp [transvectionEquiv_apply]

/-! ## (ii) — the Clifford gates as a generating set

`bigGateSet n` is the four gate families `H_k, S_k, CNOT_{ij}, CZ_{ij}` as elements of
`Pauli n ≃ₗ Pauli n`. Strategy: show each transvection lies in `closure (bigGateSet n)` (ii), get
`closure (bigGateSet n) = spSubgroup n` (with (i)), then transport to the subtype form
`SpGeneratedByCliffordGates`. -/

/-- The four Clifford gate families as a subset of `Pauli n ≃ₗ Pauli n`. -/
def bigGateSet (n : ℕ) : Set (Pauli n ≃ₗ[ZMod 2] Pauli n) :=
  (Set.range fun k : Fin n => hadamardAt k)
  ∪ (Set.range fun k : Fin n => phaseAt k)
  ∪ {g | ∃ (i j : Fin n) (h : i ≠ j), g = cnotAt i j h}
  ∪ {g | ∃ (i j : Fin n) (h : i ≠ j), g = czAt i j h}

theorem hadamardAt_mem_bigGateSet (k : Fin n) : hadamardAt k ∈ bigGateSet n :=
  Or.inl (Or.inl (Or.inl ⟨k, rfl⟩))

theorem phaseAt_mem_bigGateSet (k : Fin n) : phaseAt k ∈ bigGateSet n :=
  Or.inl (Or.inl (Or.inr ⟨k, rfl⟩))

theorem cnotAt_mem_bigGateSet (i j : Fin n) (h : i ≠ j) : cnotAt i j h ∈ bigGateSet n :=
  Or.inl (Or.inr ⟨i, j, h, rfl⟩)

theorem czAt_mem_bigGateSet (i j : Fin n) (h : i ≠ j) : czAt i j h ∈ bigGateSet n :=
  Or.inr ⟨i, j, h, rfl⟩

/-- The gates are Clifford, so the subgroup they generate sits inside `Sp(2n, 𝔽₂)`. -/
theorem closure_bigGateSet_le_spSubgroup :
    Subgroup.closure (bigGateSet n) ≤ spSubgroup n := by
  rw [Subgroup.closure_le]
  rintro g (((⟨k, rfl⟩ | ⟨k, rfl⟩) | ⟨i, j, hij, rfl⟩) | ⟨i, j, hij, rfl⟩)
  · exact mem_spSubgroup.mpr (hadamardAt_isClifford k)
  · exact mem_spSubgroup.mpr (phaseAt_isClifford k)
  · exact mem_spSubgroup.mpr (cnotAt_isClifford i j hij)
  · exact mem_spSubgroup.mpr (czAt_isClifford i j hij)

/-- A `LinearEquiv` subgroup is closed under `.trans` (the group multiplication, flipped). -/
theorem trans_mem {K : Subgroup (Pauli n ≃ₗ[ZMod 2] Pauli n)} {a b : Pauli n ≃ₗ[ZMod 2] Pauli n}
    (ha : a ∈ K) (hb : b ∈ K) : a.trans b ∈ K := mul_mem hb ha

/-- `τ_{Z_k} = S_k` is a gate. -/
theorem transvectionEquiv_pauliz_mem (k : Fin n) :
    transvectionEquiv (pauliz k) ∈ Subgroup.closure (bigGateSet n) := by
  rw [transvectionEquiv_pauliz]; exact Subgroup.subset_closure (phaseAt_mem_bigGateSet k)

/-- `τ_{Y_k} = H_k` is a gate. -/
theorem transvectionEquiv_pauliy_mem (k : Fin n) :
    transvectionEquiv (paulix k + pauliz k) ∈ Subgroup.closure (bigGateSet n) := by
  rw [transvectionEquiv_pauliy]; exact Subgroup.subset_closure (hadamardAt_mem_bigGateSet k)

/-- `τ_{X_k} = H_k S_k H_k` is a gate word. -/
theorem transvectionEquiv_paulix_mem (k : Fin n) :
    transvectionEquiv (paulix k) ∈ Subgroup.closure (bigGateSet n) := by
  rw [transvectionEquiv_paulix]
  exact trans_mem (trans_mem (inv_mem (Subgroup.subset_closure (hadamardAt_mem_bigGateSet k)))
    (Subgroup.subset_closure (phaseAt_mem_bigGateSet k)))
    (Subgroup.subset_closure (hadamardAt_mem_bigGateSet k))

/-! ## (ii), core — every transvection is a gate word

By strong induction on `(pauliSupport v).card` (the qubits where `v` is non-trivial). Base: support
`0` gives `v = 0` (`τ = 1`); support `1` gives a single-qubit Pauli (the base lemmas above). Step: a
gate strictly shrinks the support, and the conjugation law carries the transvection. -/

open scoped Classical in
/-- The set of qubits on which `v` is non-trivial. -/
noncomputable def pauliSupport (v : Pauli n) : Finset (Fin n) :=
  Finset.univ.filter (fun k => v.X k ≠ 0 ∨ v.Z k ≠ 0)

theorem mem_pauliSupport {v : Pauli n} {k : Fin n} :
    k ∈ pauliSupport v ↔ v.X k ≠ 0 ∨ v.Z k ≠ 0 := by
  classical
  simp [pauliSupport]

/-- If the support is empty, the vector is zero. -/
theorem eq_zero_of_card_pauliSupport_zero {v : Pauli n} (h : (pauliSupport v).card = 0) :
    v = 0 := by
  rw [Finset.card_eq_zero] at h
  ext k
  · by_contra hx
    have : k ∈ pauliSupport v := mem_pauliSupport.mpr (Or.inl hx)
    rw [h] at this; simp at this
  · by_contra hz
    have : k ∈ pauliSupport v := mem_pauliSupport.mpr (Or.inr hz)
    rw [h] at this; simp at this

/-- Base case: a transvection by a single-qubit Pauli is a gate word. -/
theorem transvection_mem_of_card_one {v : Pauli n} (h : (pauliSupport v).card = 1) :
    transvectionEquiv v ∈ Subgroup.closure (bigGateSet n) := by
  obtain ⟨k, hk⟩ := Finset.card_eq_one.mp h
  have hXj : ∀ j, j ≠ k → v.X j = 0 := fun j hj => by
    by_contra hx
    have hmem : j ∈ pauliSupport v := mem_pauliSupport.mpr (Or.inl hx)
    rw [hk, Finset.mem_singleton] at hmem; exact hj hmem
  have hZj : ∀ j, j ≠ k → v.Z j = 0 := fun j hj => by
    by_contra hz
    have hmem : j ∈ pauliSupport v := mem_pauliSupport.mpr (Or.inr hz)
    rw [hk, Finset.mem_singleton] at hmem; exact hj hmem
  have hkmem : v.X k ≠ 0 ∨ v.Z k ≠ 0 := by
    have : k ∈ pauliSupport v := hk ▸ Finset.mem_singleton_self k
    rwa [mem_pauliSupport] at this
  have hdich : ∀ z : ZMod 2, z = 0 ∨ z = 1 := by decide
  rcases hdich (v.X k) with hxk | hxk <;> rcases hdich (v.Z k) with hzk | hzk
  · rcases hkmem with h' | h'
    · exact absurd hxk h'
    · exact absurd hzk h'
  · have hv : v = pauliz k := by
      ext j
      · rcases eq_or_ne j k with rfl | hj
        · simp [pauliz_X, hxk]
        · simp [pauliz_X, hXj j hj]
      · rcases eq_or_ne j k with rfl | hj
        · simp [pauliz_Z, hzk, Pi.single_eq_same]
        · simp [pauliz_Z, hZj j hj, Pi.single_eq_of_ne hj]
    rw [hv]; exact transvectionEquiv_pauliz_mem k
  · have hv : v = paulix k := by
      ext j
      · rcases eq_or_ne j k with rfl | hj
        · simp [paulix_X, hxk, Pi.single_eq_same]
        · simp [paulix_X, hXj j hj, Pi.single_eq_of_ne hj]
      · rcases eq_or_ne j k with rfl | hj
        · simp [paulix_Z, hzk]
        · simp [paulix_Z, hZj j hj]
    rw [hv]; exact transvectionEquiv_paulix_mem k
  · have hv : v = paulix k + pauliz k := by
      ext j
      · rcases eq_or_ne j k with rfl | hj
        · simp [X_add, paulix_X, pauliz_X, hxk, Pi.single_eq_same]
        · simp [X_add, paulix_X, pauliz_X, hXj j hj, Pi.single_eq_of_ne hj]
      · rcases eq_or_ne j k with rfl | hj
        · simp [Z_add, paulix_Z, pauliz_Z, hzk, Pi.single_eq_same]
        · simp [Z_add, paulix_Z, pauliz_Z, hZj j hj, Pi.single_eq_of_ne hj]
    rw [hv]; exact transvectionEquiv_pauliy_mem k

/-- **Normalize a pivot to pure-X.** For `p` in the support, a single-qubit gate (`1`, `H_p`, or
`S_p`) maps qubit `p` to `(X, Z) = (1, 0)` and touches no other qubit. (`H_p` for pure-`Z`, `S_p`
for `Y` — the char-2 pre-step.) -/
theorem exists_normalize (v : Pauli n) (p : Fin n) (hp : p ∈ pauliSupport v) :
    ∃ g, g ∈ Subgroup.closure (bigGateSet n) ∧ (g v).X p = 1 ∧ (g v).Z p = 0 ∧
      ∀ q, q ≠ p → (g v).X q = v.X q ∧ (g v).Z q = v.Z q := by
  rw [mem_pauliSupport] at hp
  have dich : ∀ z : ZMod 2, z = 0 ∨ z = 1 := by decide
  rcases dich (v.X p) with hx | hx
  · -- v.X p = 0 ⟹ v.Z p = 1 (pure Z): use H_p
    have hz : v.Z p = 1 := by
      rcases hp with h | h
      · exact absurd hx h
      · rcases dich (v.Z p) with h0 | h1
        · exact absurd h0 h
        · exact h1
    refine ⟨hadamardAt p, Subgroup.subset_closure (hadamardAt_mem_bigGateSet p), ?_, ?_,
      fun q hq => ?_⟩
    · simp [hadamardAt_X, hz]
    · simp [hadamardAt_Z, hx]
    · exact ⟨by simp [hadamardAt_X, Function.update_of_ne hq],
        by simp [hadamardAt_Z, Function.update_of_ne hq]⟩
  · rcases dich (v.Z p) with hz | hz
    · -- (1, 0) pure X: identity
      exact ⟨1, Subgroup.one_mem _, hx, hz, fun q _ => ⟨rfl, rfl⟩⟩
    · -- (1, 1) Y: use S_p
      refine ⟨phaseAt p, Subgroup.subset_closure (phaseAt_mem_bigGateSet p), ?_, ?_,
        fun q hq => ?_⟩
      · simp [phaseAt_X, hx]
      · rw [phaseAt_Z, Function.update_self, hz, hx]; decide
      · exact ⟨by simp [phaseAt_X],
          by simp [phaseAt_Z, Function.update_of_ne hq]⟩

/-- `CNOT_{ij}` on two pure-`X` qubits clears target `j`, keeps control `i`, fixes the rest. -/
theorem cnot_clears {w : Pauli n} {i j : Fin n} (hij : i ≠ j)
    (hwi : w.X i = 1) (hwj : w.X j = 1) (hwjZ : w.Z j = 0) :
    (cnotAt i j hij w).X j = 0 ∧ (cnotAt i j hij w).Z j = 0 ∧ (cnotAt i j hij w).X i = 1 ∧
      ∀ q, q ≠ i → q ≠ j → (cnotAt i j hij w).X q = w.X q ∧ (cnotAt i j hij w).Z q = w.Z q := by
  refine ⟨?_, ?_, ?_, fun q hqi hqj => ?_⟩
  · rw [cnotAt_X, Function.update_self, hwj, hwi]; decide
  · rw [cnotAt_Z, Function.update_of_ne (Ne.symm hij)]; exact hwjZ
  · rw [cnotAt_X, Function.update_of_ne hij]; exact hwi
  · exact ⟨by rw [cnotAt_X, Function.update_of_ne hqj],
      by rw [cnotAt_Z, Function.update_of_ne hqi]⟩

/-- **Support reduction.** With two support qubits `i ≠ j`, a `≤ 3`-gate word (normalize `i`,
normalize `j`, then `CNOT_{ij}`) strictly shrinks the support. -/
theorem support_reduction {v : Pauli n} {i j : Fin n} (hij : i ≠ j)
    (hi : i ∈ pauliSupport v) (hj : j ∈ pauliSupport v) :
    ∃ g, g ∈ Subgroup.closure (bigGateSet n) ∧
      (pauliSupport (g v)).card < (pauliSupport v).card := by
  obtain ⟨gi, hgi_mem, hgiX, hgiZ, hgi_off⟩ := exists_normalize v i hi
  have hjgi : j ∈ pauliSupport (gi v) := by
    rw [mem_pauliSupport, (hgi_off j (Ne.symm hij)).1, (hgi_off j (Ne.symm hij)).2]
    rwa [mem_pauliSupport] at hj
  obtain ⟨gj, hgj_mem, hgjX, hgjZ, hgj_off⟩ := exists_normalize (gi v) j hjgi
  refine ⟨cnotAt i j hij * gj * gi, mul_mem (mul_mem
    (Subgroup.subset_closure (cnotAt_mem_bigGateSet i j hij)) hgj_mem) hgi_mem, ?_⟩
  set w := gj (gi v) with hwdef
  have hwiX : w.X i = 1 := by rw [(hgj_off i hij).1, hgiX]
  have hwiZ : w.Z i = 0 := by rw [(hgj_off i hij).2, hgiZ]
  have hgv : (cnotAt i j hij * gj * gi) v = cnotAt i j hij w := by
    simp only [LinearEquiv.mul_apply]; rw [hwdef]
  rw [hgv]
  obtain ⟨hcjX, hcjZ, hciX, hc_off⟩ := cnot_clears hij hwiX hgjX hgjZ
  have hsub : pauliSupport (cnotAt i j hij w) ⊆ (pauliSupport v).erase j := by
    intro k hk
    rw [mem_pauliSupport] at hk
    have hkj : k ≠ j := by
      rintro rfl
      exact hk.elim (fun h => h hcjX) (fun h => h hcjZ)
    rw [Finset.mem_erase]
    refine ⟨hkj, ?_⟩
    by_cases hki : k = i
    · subst hki; exact hi
    · rw [mem_pauliSupport]
      have e1 := hc_off k hki hkj
      have e2 := hgj_off k hkj
      have e3 := hgi_off k hki
      rw [e1.1, e1.2, e2.1, e2.2, e3.1, e3.2] at hk
      exact hk
  calc (pauliSupport (cnotAt i j hij w)).card
      ≤ ((pauliSupport v).erase j).card := Finset.card_le_card hsub
    _ < (pauliSupport v).card := Finset.card_erase_lt_of_mem hj

/-- Strong-induction helper for `transvection_mem`: a bound on the support card suffices. -/
private theorem transvection_mem_aux : ∀ (N : ℕ) (v : Pauli n),
    (pauliSupport v).card ≤ N → transvectionEquiv v ∈ Subgroup.closure (bigGateSet n) := by
  intro N
  induction N using Nat.strong_induction_on with
  | _ N ih =>
    intro v hv
    rcases Nat.lt_or_ge (pauliSupport v).card 2 with hlt | hge
    · have hc : (pauliSupport v).card = 0 ∨ (pauliSupport v).card = 1 := by omega
      rcases hc with h | h
      · rw [eq_zero_of_card_pauliSupport_zero h, transvectionEquiv_zero]; exact one_mem _
      · exact transvection_mem_of_card_one h
    · obtain ⟨i, hi, j, hj, hij⟩ := Finset.one_lt_card.mp hge
      obtain ⟨g, hg_mem, hcard⟩ := support_reduction hij hi hj
      have hgcliff : IsClifford (g : Pauli n ≃ₗ[ZMod 2] Pauli n) :=
        mem_spSubgroup.mp (closure_bigGateSet_le_spSubgroup hg_mem)
      have hIH : transvectionEquiv (g v) ∈ Subgroup.closure (bigGateSet n) :=
        ih (pauliSupport (g v)).card (lt_of_lt_of_le hcard hv) (g v) le_rfl
      have hmul : transvectionEquiv (g v) = g * transvectionEquiv v * g⁻¹ := by
        rw [transvectionEquiv_conj hgcliff v]; rfl
      have heq : transvectionEquiv v = g⁻¹ * transvectionEquiv (g v) * g := by
        rw [hmul]; group
      rw [heq]
      exact mul_mem (mul_mem (inv_mem hg_mem) hIH) hg_mem

/-- **(ii)** Every Pauli transvection is a word in the standard gates `{H, S, CNOT, CZ}`. -/
theorem transvection_mem (v : Pauli n) :
    transvectionEquiv v ∈ Subgroup.closure (bigGateSet n) :=
  transvection_mem_aux _ v le_rfl

/-- **(i) + (ii).** The standard gates generate the full symplectic group:
`⟨H, S, CNOT, CZ⟩ = Sp`. -/
theorem closure_bigGateSet_eq_spSubgroup :
    Subgroup.closure (bigGateSet n) = spSubgroup n := by
  apply le_antisymm closure_bigGateSet_le_spSubgroup
  rw [← transvectionEquiv_closure_eq_spSubgroup, Subgroup.closure_le]
  rintro h ⟨v, rfl⟩
  exact transvection_mem v

/-- **Discharges `SpGeneratedByCliffordGates`.** Transporting `⟨H, S, CNOT, CZ⟩ = Sp` from `G` up to
the subtype `↥(spSubgroup n)` (via closure induction; proof-irrelevance makes the subtype
reconstruction definitional), the elementary Clifford gates generate `Sp(2n, 𝔽₂)`. This is the
char-2 symplectic-generation input to the surjectivity of `cliffordToSp`; the Hilbert-side gate
lifts are `FTQCLib.Hilbert.cliffordGateGens_subset_range`. -/
theorem spGeneratedByCliffordGates (n : ℕ) : SpGeneratedByCliffordGates n := by
  rw [SpGeneratedByCliffordGates, Subgroup.eq_top_iff']
  rintro ⟨T, hT⟩
  suffices h : ∀ x : Pauli n ≃ₗ[ZMod 2] Pauli n, x ∈ Subgroup.closure (bigGateSet n) →
      ∀ hx : x ∈ spSubgroup n,
        (⟨x, hx⟩ : spSubgroup n) ∈ Subgroup.closure (cliffordGateGens n) by
    exact h T (by rw [closure_bigGateSet_eq_spSubgroup]; exact hT) hT
  intro x hxc
  induction hxc using Subgroup.closure_induction with
  | mem y hy =>
    intro h
    apply Subgroup.subset_closure
    rcases hy with (((⟨k, rfl⟩ | ⟨k, rfl⟩) | ⟨i, j, hij, rfl⟩) | ⟨i, j, hij, rfl⟩)
    · exact Or.inl (Or.inl (Or.inl ⟨k, Subtype.ext rfl⟩))
    · exact Or.inl (Or.inl (Or.inr ⟨k, Subtype.ext rfl⟩))
    · exact Or.inl (Or.inr ⟨i, j, hij, Subtype.ext rfl⟩)
    · exact Or.inr ⟨i, j, hij, Subtype.ext rfl⟩
  | one => intro _; exact one_mem _
  | mul a b ha hb iha ihb =>
    intro _
    have ha' : a ∈ spSubgroup n := by rw [← closure_bigGateSet_eq_spSubgroup]; exact ha
    have hb' : b ∈ spSubgroup n := by rw [← closure_bigGateSet_eq_spSubgroup]; exact hb
    exact mul_mem (iha ha') (ihb hb')
  | inv a ha iha =>
    intro _
    have ha' : a ∈ spSubgroup n := by rw [← closure_bigGateSet_eq_spSubgroup]; exact ha
    exact inv_mem (iha ha')

end FTQCLib.Gates
