/-
Copyright (c) 2026 Sam Snowden. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sam Snowden
-/
import FTQCLib.Pauli.Basis
import FTQCLib.Gates.Hadamard
import FTQCLib.Gates.Phase
import FTQCLib.Gates.CNOT
import FTQCLib.Gates.CZ

set_option linter.unusedSectionVars false

/-! # The Clifford group on `n` qubits

A Clifford operator on `n` qubits is (modulo phase) a unitary that
normalises the Pauli group: conjugation by it sends Pauli operators to
Pauli operators. In the binary-symplectic representation this is exactly
the group of `(ZMod 2)`-linear automorphisms of `Pauli n` that preserve
the symplectic form `omegaBilin`. That group is the symplectic group
`Sp(2n, F_2)`.

The four files

* `FTQCLib/Gates/Hadamard.lean`
* `FTQCLib/Gates/Phase.lean`
* `FTQCLib/Gates/CNOT.lean`
* `FTQCLib/Gates/CZ.lean`

define the four standard Clifford generators on the binary-symplectic
representation as `(ZMod 2)`-linear automorphisms of `Pauli n` and prove
each preserves `omegaBilin`. This file packages the predicate

  `IsClifford T := IsSymplecticEquiv omegaBilin T`

and records the four generators as Cliffords.

The Clifford group is generated by `{H, S, CNOT}`; `CZ = (I ⊗ H)·CNOT·(I ⊗ H)`
is a derived gate but is also recorded here directly because of its
prominence in CSS code constructions and in the SIMD-C bicycle / tricycle
architecture.
-/

namespace FTQCLib.Gates

open FTQCLib.Pauli

variable {n : ℕ}

/-- A `(ZMod 2)`-linear automorphism `T : Pauli n ≃ₗ[ZMod 2] Pauli n` is
**Clifford** iff it preserves the symplectic form `omegaBilin`, i.e.\
`omega (T p) (T q) = omega p q` for all `p, q`. Equivalently, conjugation
by the corresponding unitary sends every Pauli operator to a Pauli
operator (modulo phase).

The set of Cliffords forms a group under composition; in the
binary-symplectic representation it is exactly
`Sp(2n, F_2) = Aut(Pauli n, omegaBilin)`. -/
def IsClifford (T : Pauli n ≃ₗ[ZMod 2] Pauli n) : Prop :=
  IsSymplecticEquiv (omegaBilin (n := n)) T

/-- The identity is Clifford. -/
theorem isClifford_refl : IsClifford (LinearEquiv.refl (ZMod 2) (Pauli n)) :=
  fun _ _ => rfl

/-- Cliffords compose to Cliffords. -/
theorem IsClifford.trans {T U : Pauli n ≃ₗ[ZMod 2] Pauli n}
    (hT : IsClifford T) (hU : IsClifford U) :
    IsClifford (T.trans U) := by
  intro p q
  -- Unfold T.trans = U ∘ T, then apply hU then hT.
  change omegaBilin (U (T p)) (U (T q)) = omegaBilin p q
  rw [hU, hT]

/-- The Hadamard gate on qubit `k` is Clifford. -/
theorem hadamardAt_isClifford (k : Fin n) :
    IsClifford (hadamardAt k) :=
  hadamardAt_isSymplecticEquiv k

/-- The phase gate `S` on qubit `k` is Clifford. -/
theorem phaseAt_isClifford (k : Fin n) :
    IsClifford (phaseAt k) :=
  phaseAt_isSymplecticEquiv k

/-- The CNOT gate with control `i` and target `j` (`i ≠ j`) is Clifford. -/
theorem cnotAt_isClifford (i j : Fin n) (hij : i ≠ j) :
    IsClifford (cnotAt i j hij) :=
  cnotAt_isSymplecticEquiv i j hij

/-- The CZ gate on distinct qubits `i ≠ j` is Clifford. -/
theorem czAt_isClifford (i j : Fin n) (hij : i ≠ j) :
    IsClifford (czAt i j hij) :=
  czAt_isSymplecticEquiv i j hij

end FTQCLib.Gates
